// Sprint 68 — Spousal Lifetime Access Trust (SLAT) Module
//
// A SLAT is an irrevocable trust funded by one spouse (grantor) for the benefit
// of the other spouse (beneficiary spouse) and descendants. Assets transferred
// to the SLAT are removed from the grantor's gross estate, but the beneficiary
// spouse retains indirect access via distributions.
//
// Key risks modeled:
//   - Grantor drag: if trust is a grantor trust, income tax paid by grantor
//     further reduces the taxable estate (a feature, not a bug)
//   - Divorce flag: if spouses divorce, grantor loses indirect access entirely
//   - Reciprocal trust doctrine: if both spouses create SLATs for each other,
//     IRS may uncross them and include both in respective estates

import { ProjectionScenario } from '@/lib/types/projection-scenario'

export interface SLATConfig {
  // Amount transferred into the SLAT
  fundingAmount: number
  // Year SLAT is established
  establishmentYear: number
  // Projected annual growth rate of SLAT assets
  growthRate: number
  // Whether SLAT is structured as a grantor trust (grantor pays income tax)
  isGrantorTrust: boolean
  // Estimated annual income generated by SLAT assets (for grantor drag calc)
  estimatedAnnualIncome: number
  // Marginal income tax rate of grantor
  grantorMarginalRate: number
  // Whether a second SLAT exists for the other spouse (reciprocal trust risk)
  hasReciprocalSLAT: boolean
  // Death year for projection
  deathYear: number
  // Federal exemption available at establishment (from federal_tax_config)
  federalExemptionAtEstablishment: number
}

export interface SLATResult {
  // Assets removed from gross estate at funding
  estateReductionAtFunding: number
  // Projected SLAT value at death year
  slatValueAtDeath: number
  // Total income tax paid by grantor over projection period (grantor drag benefit)
  totalGrantorDrag: number
  // Net estate reduction including grantor drag
  netEstateReduction: number
  // §2035 flag: SLAT funded within 3 years of death (unlikely but flag if so)
  section2035Flag: boolean
  // Whether reciprocal trust doctrine warning should be shown
  reciprocalTrustWarning: boolean
  // Divorce risk flag
  divorceRiskNote: string
  // Advisory notes
  advisoryNotes: string[]
}

export function applySLAT(
  scenario: ProjectionScenario,
  config: SLATConfig
): SLATResult {
  const {
    fundingAmount,
    establishmentYear,
    growthRate,
    isGrantorTrust,
    estimatedAnnualIncome,
    grantorMarginalRate,
    hasReciprocalSLAT,
    deathYear,
    federalExemptionAtEstablishment,
  } = config

  const advisoryNotes: string[] = []
  const yearsToGrow = deathYear - establishmentYear

  // SLAT assets grow outside the gross estate
  const slatValueAtDeath = fundingAmount * Math.pow(1 + growthRate, yearsToGrow)

  // Grantor drag: grantor pays income tax on trust income, further depleting estate
  // This is a planning benefit — each dollar of tax paid by grantor is effectively
  // a tax-free gift to the trust beneficiaries
  const annualGrantorDrag = isGrantorTrust
    ? estimatedAnnualIncome * grantorMarginalRate
    : 0
  const totalGrantorDrag = annualGrantorDrag * yearsToGrow

  const netEstateReduction = fundingAmount + totalGrantorDrag

  // §2035: unlikely for SLATs (not life insurance) but flag if within 3 years
  const section2035Flag = deathYear - establishmentYear <= 3

  // Reciprocal trust doctrine warning
  const reciprocalTrustWarning = hasReciprocalSLAT

  // Advisory notes
  if (fundingAmount > federalExemptionAtEstablishment) {
    advisoryNotes.push(
      `SLAT funding of $${fundingAmount.toLocaleString()} exceeds the available federal exemption ` +
      `of $${federalExemptionAtEstablishment.toLocaleString()}. Excess funding will use lifetime exemption ` +
      `and may trigger gift tax if exemption is exhausted.`
    )
  }

  if (isGrantorTrust) {
    advisoryNotes.push(
      `Grantor trust status allows the grantor to pay income tax on trust earnings — effectively ` +
      `an additional tax-free gift of $${Math.round(totalGrantorDrag).toLocaleString()} over the projection period.`
    )
  }

  if (reciprocalTrustWarning) {
    advisoryNotes.push(
      `⚠️ Reciprocal Trust Doctrine Risk: Both spouses have SLATs for each other. ` +
      `The IRS may argue these trusts are reciprocal and uncross them, causing both to be ` +
      `included in the respective grantors' estates. Ensure SLATs differ in material terms ` +
      `(funding amounts, trustees, distribution standards, or establishment dates).`
    )
  }

  advisoryNotes.push(
    `If the Chens divorce, ${config.isGrantorTrust ? 'the grantor' : 'the funding spouse'} loses ` +
    `indirect access to SLAT assets. Consider a trustee distribution standard that addresses this risk.`
  )

  if (section2035Flag) {
    advisoryNotes.push(
      `⚠️ SLAT established within 3 years of the selected death year. ` +
      `While §2035 typically applies to life insurance, early establishment is strongly preferred.`
    )
  }

  return {
    estateReductionAtFunding: fundingAmount,
    slatValueAtDeath,
    totalGrantorDrag,
    netEstateReduction,
    section2035Flag,
    reciprocalTrustWarning,
    divorceRiskNote: 'If spouses divorce, grantor loses indirect access to SLAT assets via beneficiary spouse distributions.',
    advisoryNotes,
  }
}
