import type { EventContent } from './types'
import { EVENT_CONTENT_SPRINT5 } from './content-sprint5'

export const EVENT_CONTENT: Record<string, EventContent> = {
  'selling-a-business': {
    slug: 'selling-a-business',
    title: 'Selling a Business',
    shortTitle: 'Business Sale',
    category: 'business',
    urgency: 'critical',
    heroLine: 'A business sale is the highest-stakes estate planning moment most owners will ever face.',
    subhead: 'When a business represents 60–80% of your net worth, a sale can double your taxable estate overnight. The window to act — GRAT funding, charitable timing, gifting before valuation spikes — closes at signing. Most owners learn this too late.',
    whatChanges: [
      'Your gross estate may cross federal and state estate tax thresholds in a single transaction',
      'Liquidity event creates a narrow window for GRATs, SLATs, and charitable vehicles',
      'Capital gains exposure depends on deal structure (asset vs stock sale, installment treatment)',
      'Existing beneficiary designations and titling may not reflect post-sale asset mix',
      'Estate documents written when the business was worth less need immediate review',
    ],
    actions: [
      {
        priority: 1,
        title: 'Model your post-sale estate tax exposure',
        description: 'Run your estate tax snapshot with the expected proceeds as liquid assets. Most owners are shocked by the number.',
        linkedFeature: '/estate-tax',
        urgencyDays: 7,
      },
      {
        priority: 1,
        title: 'Contact an estate attorney before signing',
        description: 'GRAT funding windows, irrevocable trust strategies, and charitable timing must be executed before or at closing — not after.',
        professionalType: 'attorney',
        urgencyDays: 14,
      },
      {
        priority: 2,
        title: 'Review your gifting capacity before valuation spikes',
        description: 'Annual exclusion gifts and lifetime exemption usage are most efficient before the sale closes at peak value.',
        linkedFeature: '/my-estate-trust-strategy?tab=gifting',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Update titling and beneficiary designations',
        description: 'Proceeds will flow into accounts that may have outdated designations or sub-optimal titling for your post-sale estate.',
        linkedFeature: '/titling',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Build a post-sale income and withdrawal strategy',
        description: 'Selling a business often eliminates a primary income source. Model your retirement projections with proceeds as the asset base.',
        linkedFeature: '/projections',
      },
    ],
    assessmentQuestions: [
      {
        id: 'bs1',
        question: 'Do you know your estimated post-sale estate tax exposure?',
        options: [
          { label: 'Yes — modeled with an advisor or attorney', score: 3 },
          { label: 'Roughly — based on my own estimates', score: 2 },
          { label: 'Not yet — I know I should', score: 1, hint: 'This is the highest-priority item before closing' },
          { label: 'No and I don\'t know where to start', score: 0 },
        ],
      },
      {
        id: 'bs2',
        question: 'Have you discussed irrevocable trust strategies (GRAT, SLAT, ILIT) before the sale closes?',
        options: [
          { label: 'Yes — strategies are in place or in motion', score: 3 },
          { label: 'In conversation with an attorney now', score: 2 },
          { label: 'I\'ve heard of them but haven\'t acted', score: 1 },
          { label: 'No — this is new to me', score: 0 },
        ],
      },
      {
        id: 'bs3',
        question: 'Is your will and estate plan current for the post-sale asset level?',
        options: [
          { label: 'Yes — reviewed in the last 2 years', score: 3 },
          { label: 'Current will but written before the business reached this value', score: 1, hint: 'A will written at $2M may be inadequate at $8M' },
          { label: 'Old or incomplete documents', score: 0 },
          { label: 'No will or estate plan', score: 0 },
        ],
      },
      {
        id: 'bs4',
        question: 'Have you reviewed beneficiary designations on accounts that will receive sale proceeds?',
        options: [
          { label: 'Yes — all designations reviewed and current', score: 3 },
          { label: 'Some reviewed but not all', score: 2 },
          { label: 'Set originally but never updated', score: 1 },
          { label: 'Unsure what my designations say', score: 0 },
        ],
      },
      {
        id: 'bs5',
        question: 'Do you have a post-sale income strategy (withdrawal sequencing, Roth conversion window, RMD planning)?',
        options: [
          { label: 'Yes — modeled with a financial advisor', score: 3 },
          { label: 'General idea but not formally modeled', score: 2 },
          { label: 'Planning to figure it out after the sale', score: 1, hint: 'Post-sale sequencing decisions are best made before liquidity arrives' },
          { label: 'No — haven\'t thought about it', score: 0 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Selling a Business: Estate Planning Guide for $2M–$30M Owners',
    seoDescription: 'What changes for your estate when you sell a business. GRAT windows, estate tax exposure, beneficiary updates, and what to do before closing.',
    relatedSlugs: ['large-rsu-vest', 'approaching-retirement'],
  },

  'death-of-spouse': {
    slug: 'death-of-spouse',
    title: 'Death of a Spouse',
    shortTitle: 'Spouse Death',
    category: 'family',
    urgency: 'critical',
    heroLine: 'The death of a spouse triggers legal and financial deadlines most surviving spouses don\'t know exist.',
    subhead: 'Portability election for the federal estate tax exemption must be filed within 9 months. Retitling of jointly-held assets, beneficiary updates, and trust funding have their own clocks. The cost of missing these windows is permanent.',
    whatChanges: [
      'Federal portability election (Form 706) must be filed within 9 months to preserve the deceased spouse\'s unused exemption',
      'Jointly-held property must be retitled — the method affects estate tax and step-up in basis',
      'Beneficiary designations on IRAs, 401(k)s, and insurance policies control asset flow — not the will',
      'If a revocable trust exists, it may bifurcate into separate trusts requiring funding and administration',
      'Social Security survivor benefits have election windows that affect lifetime income',
    ],
    actions: [
      {
        priority: 1,
        title: 'File or calendar the portability election deadline',
        description: 'The IRS allows a 9-month window (extendable to 15 months) to elect portability of the deceased spouse\'s unused federal exemption. Missing this is irreversible.',
        professionalType: 'attorney',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Inventory and retitle jointly-held assets',
        description: 'JTWROS property passes automatically but must be retitled. Community property has different basis rules. Each asset type has different treatment.',
        linkedFeature: '/titling',
        urgencyDays: 60,
      },
      {
        priority: 1,
        title: 'Update all beneficiary designations',
        description: 'Your spouse was likely the primary beneficiary on most accounts. Every designation must be reviewed and updated immediately.',
        linkedFeature: '/titling',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Evaluate Social Security survivor benefit timing',
        description: 'Survivor benefits can be claimed as early as 60. Coordinating with your own benefit can significantly affect lifetime income.',
        linkedFeature: '/social-security',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Update your own estate plan as a single person',
        description: 'Guardian designations, trust structures, and distribution plans written for a married couple need immediate review.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'ds1',
        question: 'Have you been advised about the federal portability election deadline?',
        options: [
          { label: 'Yes — attorney is handling it', score: 3 },
          { label: 'I know about it but haven\'t acted', score: 1, hint: '9-month window from date of death' },
          { label: 'This is the first I\'m hearing of it', score: 0 },
          { label: 'Not applicable — estate below federal threshold', score: 3 },
        ],
      },
      {
        id: 'ds2',
        question: 'Have you reviewed beneficiary designations on all accounts?',
        options: [
          { label: 'Yes — all updated', score: 3 },
          { label: 'In process', score: 2 },
          { label: 'Not yet started', score: 0 },
          { label: 'Unsure what the designations say', score: 0 },
        ],
      },
      {
        id: 'ds3',
        question: 'Have jointly-held assets been retitled into your name or the appropriate trust?',
        options: [
          { label: 'Yes — all retitled with legal guidance', score: 3 },
          { label: 'Some retitled, others pending', score: 2 },
          { label: 'Not yet — unsure where to start', score: 0 },
          { label: 'I didn\'t know this was necessary', score: 0 },
        ],
      },
      {
        id: 'ds4',
        question: 'Have you evaluated Social Security survivor benefit options?',
        options: [
          { label: 'Yes — reviewed with an advisor', score: 3 },
          { label: 'I know I need to but haven\'t yet', score: 1 },
          { label: 'No — I didn\'t know this was a decision', score: 0 },
          { label: 'Already receiving survivor benefits', score: 3 },
        ],
      },
      {
        id: 'ds5',
        question: 'Has your own estate plan been reviewed and updated as a surviving spouse?',
        options: [
          { label: 'Yes — reviewed and updated', score: 3 },
          { label: 'Scheduled with an attorney', score: 2 },
          { label: 'Not yet — it feels too soon', score: 1, hint: 'Understandable — but some decisions are time-sensitive' },
          { label: 'No and I\'m not sure when to do this', score: 0 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Death of a Spouse: Estate Planning Checklist for Surviving Spouses',
    seoDescription: 'Portability election deadlines, retitling, beneficiary updates, and Social Security decisions after losing a spouse. What to do and when.',
    relatedSlugs: ['serious-diagnosis', 'approaching-retirement'],
  },

  'serious-diagnosis': {
    slug: 'serious-diagnosis',
    title: 'Serious Health Diagnosis',
    shortTitle: 'Health Diagnosis',
    category: 'health',
    urgency: 'critical',
    heroLine: 'A serious diagnosis makes incapacity planning urgent — not someday, right now.',
    subhead: 'Healthcare directives, durable power of attorney, and trust funding must be in place before cognitive or physical capacity is diminished. Once incapacity occurs, these documents cannot be signed. Courts step in instead.',
    whatChanges: [
      'Durable Power of Attorney must be signed while you have legal capacity — courts control assets without it',
      'Healthcare Proxy and Advance Directive specify your wishes and designate decision-makers',
      'Revocable trusts should be funded now so assets transfer without probate if something happens',
      'Life insurance and long-term care coverage should be reviewed for adequacy',
      'Gifting strategies that reduce the taxable estate may need to be executed sooner',
    ],
    actions: [
      {
        priority: 1,
        title: 'Execute Durable POA and Healthcare Directive immediately',
        description: 'These documents must be signed while you have legal capacity. An attorney can often facilitate emergency signings within days.',
        professionalType: 'attorney',
        urgencyDays: 14,
        linkedFeature: '/incapacity-planning',
      },
      {
        priority: 1,
        title: 'Fund your revocable trust',
        description: 'Assets held in your name — not the trust — will go through probate. Funding the trust now ensures your plan controls asset distribution.',
        professionalType: 'attorney',
        urgencyDays: 30,
        linkedFeature: '/titling',
      },
      {
        priority: 2,
        title: 'Review life insurance adequacy',
        description: 'Confirm death benefit amounts, ILIT ownership structure if applicable, and that beneficiary designations are current.',
        linkedFeature: '/insurance',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Accelerate any planned gifting',
        description: 'Annual exclusion gifts and lifetime exemption usage may be more urgent now. Consider whether irrevocable trust strategies should be executed sooner.',
        professionalType: 'attorney',
        linkedFeature: '/my-estate-trust-strategy?tab=gifting',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Update your estate plan for the current situation',
        description: 'Guardian designations, trust distributions, and specific bequests may need to reflect current family circumstances.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'sd1',
        question: 'Do you have a current Durable Power of Attorney?',
        options: [
          { label: 'Yes — signed and current', score: 3 },
          { label: 'Old one — may not be current', score: 1, hint: 'Some institutions refuse POAs older than 3 years' },
          { label: 'No — haven\'t done this yet', score: 0, hint: 'This is the most urgent item' },
          { label: 'Unsure', score: 0 },
        ],
      },
      {
        id: 'sd2',
        question: 'Do you have a Healthcare Directive or Living Will?',
        options: [
          { label: 'Yes — current and known to my doctor and family', score: 3 },
          { label: 'Yes — but I\'m not sure it\'s current or accessible', score: 1 },
          { label: 'No', score: 0 },
          { label: 'In process with an attorney', score: 2 },
        ],
      },
      {
        id: 'sd3',
        question: 'Are your major assets titled in a trust or have a designated beneficiary?',
        options: [
          { label: 'Yes — revocable trust funded and current', score: 3 },
          { label: 'Partial — some assets in trust, others not', score: 1 },
          { label: 'No trust — assets in my name only', score: 0, hint: 'Probate risk is significant without trust or beneficiary designations' },
          { label: 'Unsure how my assets are titled', score: 0 },
        ],
      },
      {
        id: 'sd4',
        question: 'Does your family know where your documents are and what they say?',
        options: [
          { label: 'Yes — everything documented and accessible', score: 3 },
          { label: 'Some family members know, not all', score: 2 },
          { label: 'No — this isn\'t organized', score: 0 },
          { label: 'I have documents but haven\'t shared the details', score: 1 },
        ],
      },
      {
        id: 'sd5',
        question: 'Have you spoken with your estate attorney about accelerating any planning given your diagnosis?',
        options: [
          { label: 'Yes — meeting scheduled or completed', score: 3 },
          { label: 'Not yet but I have an attorney', score: 1 },
          { label: 'I don\'t have an estate attorney', score: 0, hint: 'This is the time to find one quickly' },
          { label: 'I\'m not sure what to ask them', score: 1 },
        ],
      },
    ],
    advisorCTA: false,
    attorneyCTA: true,
    seoTitle: 'Serious Health Diagnosis: Estate Planning Checklist',
    seoDescription: 'What to do with your estate plan when facing a serious diagnosis. POA, healthcare directives, trust funding, and gifting timing.',
    relatedSlugs: ['death-of-spouse', 'approaching-retirement'],
  },

  'receiving-inheritance': {
    slug: 'receiving-inheritance',
    title: 'Receiving an Inheritance',
    shortTitle: 'Inheritance',
    category: 'wealth',
    urgency: 'high',
    heroLine: 'An inheritance can push a household into estate planning complexity they\'ve never had to manage before.',
    subhead: 'Crossing the $2M threshold for the first time — or adding significantly to an existing estate — creates new federal and state tax exposure, titling decisions, and planning obligations. The decisions made in the first 90 days matter.',
    whatChanges: [
      'Inherited IRAs have strict 10-year distribution rules with significant tax implications',
      'Stepped-up basis on inherited assets affects capital gains strategy for years',
      'Your own gross estate may now face federal or state estate tax exposure',
      'Assets received as beneficiary (not through probate) skip your will but need new beneficiary designations',
      'State inheritance taxes apply in some states regardless of federal estate tax exposure',
    ],
    actions: [
      {
        priority: 1,
        title: 'Understand the inherited IRA distribution rules',
        description: 'Non-spouse beneficiaries must distribute inherited IRAs within 10 years. Annual RMD requirements within that window depend on when the original owner died.',
        professionalType: 'cpa',
        urgencyDays: 30,
        linkedFeature: '/rmd',
      },
      {
        priority: 1,
        title: 'Calculate your new gross estate and tax exposure',
        description: 'Add the inherited assets to your existing estate and run a fresh estate tax snapshot. You may have crossed a threshold that changes your planning priorities.',
        linkedFeature: '/estate-tax',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Update your own beneficiary designations',
        description: 'Assets you just inherited need their own beneficiary designations — they don\'t automatically flow to your existing plan.',
        linkedFeature: '/titling',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Review titling and basis on inherited assets',
        description: 'Stepped-up basis resets capital gains on inherited assets. Selling timing, titling into a trust, and carryover basis for IRAs all require careful coordination.',
        professionalType: 'cpa',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Review and update your estate plan for the new asset level',
        description: 'Trusts, distribution provisions, and strategies written before the inheritance may be inadequate for your current estate size.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'ri1',
        question: 'Do you understand the distribution rules for any inherited IRAs or retirement accounts?',
        options: [
          { label: 'Yes — reviewed with a CPA or advisor', score: 3 },
          { label: 'Generally — know the 10-year rule exists', score: 2 },
          { label: 'No — this is new to me', score: 0, hint: 'Mistakes here can be costly and irreversible' },
          { label: 'No inherited retirement accounts', score: 3 },
        ],
      },
      {
        id: 'ri2',
        question: 'Have you calculated your new gross estate including the inherited assets?',
        options: [
          { label: 'Yes — modeled with updated estate tax snapshot', score: 3 },
          { label: 'Rough estimate only', score: 2 },
          { label: 'Not yet', score: 0 },
          { label: 'Inheritance doesn\'t change my estate tax picture', score: 3 },
        ],
      },
      {
        id: 'ri3',
        question: 'Have you updated beneficiary designations on the inherited assets?',
        options: [
          { label: 'Yes — all updated', score: 3 },
          { label: 'In process', score: 2 },
          { label: 'No — didn\'t know I needed to', score: 0 },
          { label: 'Assets don\'t have beneficiary designations', score: 2 },
        ],
      },
      {
        id: 'ri4',
        question: 'Do you understand the stepped-up basis on inherited non-retirement assets?',
        options: [
          { label: 'Yes — accounted for in my tax planning', score: 3 },
          { label: 'Aware of it but haven\'t planned around it', score: 2 },
          { label: 'No — this is new to me', score: 0, hint: 'Basis reset can save significant capital gains taxes' },
          { label: 'No inherited non-retirement assets', score: 3 },
        ],
      },
      {
        id: 'ri5',
        question: 'Has your estate attorney reviewed your plan for the new asset level?',
        options: [
          { label: 'Yes — plan updated', score: 3 },
          { label: 'Meeting scheduled', score: 2 },
          { label: 'Not yet', score: 1 },
          { label: 'I don\'t have an estate attorney', score: 0 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Receiving an Inheritance: Estate Planning Guide for $2M+ Households',
    seoDescription: 'Inherited IRA rules, stepped-up basis, estate tax exposure, and beneficiary designations. What to do in the first 90 days after receiving an inheritance.',
    relatedSlugs: ['selling-a-business', 'large-rsu-vest'],
  },

  'divorce': {
    slug: 'divorce',
    title: 'Divorce',
    shortTitle: 'Divorce',
    category: 'family',
    urgency: 'critical',
    heroLine: 'Divorce restructures every dimension of your estate plan — most of it urgently.',
    subhead: 'Beneficiary designations, powers of attorney, and trust documents naming your spouse remain legally valid until explicitly changed. In the middle of a divorce, your ex may still control your assets if something happens to you.',
    whatChanges: [
      'Beneficiary designations naming your spouse on IRAs, 401(k)s, and life insurance remain valid until changed',
      'Your spouse may still hold Durable POA and Healthcare Proxy authority during the divorce process',
      'QDROs (Qualified Domestic Relations Orders) govern how retirement accounts are divided — timing matters',
      'Joint trusts must be bifurcated; revocable trusts may need complete restructuring',
      'Estate tax planning built around marital deduction strategies no longer applies',
    ],
    actions: [
      {
        priority: 1,
        title: 'Update beneficiary designations immediately',
        description: 'Federal law (ERISA) governs retirement accounts — state divorce law does not automatically update beneficiaries. Your ex remains the beneficiary until you change it.',
        linkedFeature: '/titling',
        urgencyDays: 14,
      },
      {
        priority: 1,
        title: 'Revoke existing POA and Healthcare Directive',
        description: 'Your spouse may still have legal authority to make financial and medical decisions for you during the divorce. New documents should be executed immediately.',
        professionalType: 'attorney',
        urgencyDays: 14,
        linkedFeature: '/incapacity-planning',
      },
      {
        priority: 1,
        title: 'Understand QDRO requirements for retirement accounts',
        description: 'Dividing 401(k)s and pension plans requires a court-approved QDRO. The process takes months — start early to avoid delays.',
        professionalType: 'attorney',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Rebuild your estate plan as a single person',
        description: 'New will, updated trust structure, revised distribution plan, and guardian designations if children are involved.',
        professionalType: 'attorney',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Model your post-divorce estate and retirement picture',
        description: 'Asset division changes your retirement projections, estate tax exposure, and Social Security strategy significantly.',
        linkedFeature: '/projections',
      },
    ],
    assessmentQuestions: [
      {
        id: 'dv1',
        question: 'Have you updated beneficiary designations on all retirement accounts and insurance policies?',
        options: [
          { label: 'Yes — all updated', score: 3 },
          { label: 'Some updated, others pending', score: 1, hint: 'ERISA law means your ex stays beneficiary until you change it' },
          { label: 'No — divorce isn\'t final yet', score: 0, hint: 'You can update beneficiaries during the divorce process' },
          { label: 'I didn\'t know I could do this before the divorce is final', score: 0 },
        ],
      },
      {
        id: 'dv2',
        question: 'Have you revoked any POA or Healthcare Directive naming your spouse?',
        options: [
          { label: 'Yes — revoked and new documents executed', score: 3 },
          { label: 'In process with my attorney', score: 2 },
          { label: 'No — hadn\'t thought about it', score: 0, hint: 'Your spouse may still have legal decision-making authority' },
          { label: 'Never had these documents', score: 1 },
        ],
      },
      {
        id: 'dv3',
        question: 'Do you understand the QDRO process for dividing retirement accounts?',
        options: [
          { label: 'Yes — QDRO is in process or complete', score: 3 },
          { label: 'My attorney is handling it', score: 3 },
          { label: 'I know what a QDRO is but haven\'t started', score: 1 },
          { label: 'No retirement accounts to divide', score: 3 },
        ],
      },
      {
        id: 'dv4',
        question: 'Have joint trusts or estate documents been restructured for your post-divorce situation?',
        options: [
          { label: 'Yes — attorney has updated everything', score: 3 },
          { label: 'Divorce isn\'t final — planning for after', score: 2 },
          { label: 'Not yet — focused on the divorce itself', score: 1 },
          { label: 'No joint estate documents existed', score: 3 },
        ],
      },
      {
        id: 'dv5',
        question: 'Have you modeled your post-divorce retirement and estate picture?',
        options: [
          { label: 'Yes — updated projections with an advisor', score: 3 },
          { label: 'General idea but not modeled', score: 2 },
          { label: 'Not yet — focused on the legal process', score: 1 },
          { label: 'No — don\'t know where to start', score: 0 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Divorce: Estate Planning Checklist for $2M–$30M Households',
    seoDescription: 'Beneficiary designations, QDROs, POA revocation, and trust restructuring during and after divorce. What to do and when.',
    relatedSlugs: ['death-of-spouse', 'receiving-inheritance'],
  },

  'approaching-retirement': {
    slug: 'approaching-retirement',
    title: 'Approaching Retirement',
    shortTitle: 'Approaching Retirement',
    category: 'retirement',
    urgency: 'high',
    heroLine: 'The 5 years before retirement are the highest-leverage planning window most people ever have.',
    subhead: 'Social Security timing, Roth conversion windows, RMD planning, and estate freeze strategies all interact in this period. Decisions made now compound for decades. Decisions deferred now cannot be undone.',
    whatChanges: [
      'Social Security claiming age affects lifetime income by $100K–$300K for many households',
      'The Roth conversion window between retirement and RMD start age (73) may never be more favorable',
      'Medicare enrollment at 65 has permanent penalty windows that cannot be reopened',
      'Estate freeze strategies (GRATs, SLATs) are most effective before asset appreciation accelerates',
      'Withdrawal sequencing from taxable, tax-deferred, and Roth accounts affects taxes for 30+ years',
    ],
    actions: [
      {
        priority: 1,
        title: 'Model Social Security claiming scenarios',
        description: 'Every year of delay between 62 and 70 increases your benefit by 6–8%. For couples, survivor benefit coordination adds another dimension.',
        linkedFeature: '/social-security',
      },
      {
        priority: 1,
        title: 'Model the Roth conversion window',
        description: 'The gap between retirement and RMD start age is often the lowest-tax period of your life. Converting tax-deferred assets now reduces future RMD burden.',
        linkedFeature: '/roth',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Confirm Medicare enrollment timing',
        description: 'The Initial Enrollment Period around your 65th birthday cannot be extended. Late enrollment causes permanent premium penalties.',
        urgencyDays: 180,
      },
      {
        priority: 2,
        title: 'Build your withdrawal sequencing strategy',
        description: 'Which accounts you draw from first — and in what order — determines your tax burden for the next 30 years.',
        linkedFeature: '/projections',
        professionalType: 'advisor',
      },
      {
        priority: 3,
        title: 'Review estate freeze opportunities before retirement',
        description: 'GRATs and other freeze strategies work best when assets are still appreciating. Retirement often marks the peak of earned income and asset growth.',
        linkedFeature: '/my-estate-trust-strategy',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'ar1',
        question: 'Have you modeled Social Security claiming scenarios for your household?',
        options: [
          { label: 'Yes — with an advisor, with spousal coordination', score: 3 },
          { label: 'Yes — on my own or using online tools', score: 2 },
          { label: 'No — I know I should', score: 1 },
          { label: 'No — I\'m not sure when I\'ll retire', score: 1 },
        ],
      },
      {
        id: 'ar2',
        question: 'Have you evaluated Roth conversion opportunities before RMDs begin?',
        options: [
          { label: 'Yes — conversion strategy in place', score: 3 },
          { label: 'Aware of the window, haven\'t acted', score: 2 },
          { label: 'No — not familiar with the strategy', score: 0, hint: 'This window closes when RMDs begin at 73' },
          { label: 'No traditional IRA or 401(k) to convert', score: 3 },
        ],
      },
      {
        id: 'ar3',
        question: 'Are you on track for Medicare enrollment at 65?',
        options: [
          { label: 'Yes — enrolled or enrollment is planned', score: 3 },
          { label: 'More than 2 years away — will address it', score: 2 },
          { label: 'Turning 65 soon and haven\'t looked into it', score: 0, hint: 'Late enrollment causes permanent premium penalties' },
          { label: 'Covered by employer health insurance past 65', score: 2 },
        ],
      },
      {
        id: 'ar4',
        question: 'Do you have a withdrawal sequencing strategy for retirement accounts?',
        options: [
          { label: 'Yes — modeled with an advisor', score: 3 },
          { label: 'General idea based on my own research', score: 2 },
          { label: 'Planning to figure it out at retirement', score: 1, hint: 'Sequencing decisions have a 30-year compounding effect' },
          { label: 'No strategy — plan to withdraw as needed', score: 0 },
        ],
      },
      {
        id: 'ar5',
        question: 'Has your estate plan been reviewed in the context of your retirement timeline?',
        options: [
          { label: 'Yes — reviewed in the last 2 years', score: 3 },
          { label: 'Old plan — hasn\'t been reviewed since assets grew', score: 1 },
          { label: 'No estate plan', score: 0 },
          { label: 'No — it\'s on the list', score: 1 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Approaching Retirement: Estate and Financial Planning Guide',
    seoDescription: 'Social Security timing, Roth conversion windows, Medicare enrollment, and estate freeze strategies. The 5-year pre-retirement planning checklist.',
    relatedSlugs: ['large-rsu-vest', 'death-of-spouse'],
  },

  'large-rsu-vest': {
    slug: 'large-rsu-vest',
    title: 'Large RSU Vest or Liquidity Event',
    shortTitle: 'RSU / Liquidity Event',
    category: 'wealth',
    urgency: 'high',
    heroLine: 'A large RSU vest or IPO/acquisition event can double your taxable estate in a single year.',
    subhead: 'Concentrated stock positions, sudden liquidity, and rapid estate growth create a narrow window for capital gains management, gifting strategy, and estate planning. Most executives wait too long.',
    whatChanges: [
      'Ordinary income tax applies to RSU vest value at time of delivery — separate from capital gains on subsequent appreciation',
      'Concentrated position in employer stock creates both investment risk and estate planning complexity',
      'Gross estate may cross federal or state estate tax thresholds for the first time',
      'Gifting strategies are most effective before additional appreciation — the window is now',
      'Existing estate plan may not account for the new asset level or liquidity',
    ],
    actions: [
      {
        priority: 1,
        title: 'Model your new estate tax exposure',
        description: 'Add vested shares at current value to your gross estate and run the estate tax snapshot. If you\'ve crossed a threshold, the planning conversation changes.',
        linkedFeature: '/estate-tax',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Evaluate concentrated position strategy',
        description: 'Holding concentrated employer stock adds investment risk to estate risk. Exchange funds, charitable vehicles, and staged diversification each have different tax profiles.',
        professionalType: 'advisor',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Use the post-vest window for gifting',
        description: 'Gifting shares before further appreciation uses less lifetime exemption. Annual exclusion gifts of stock are most efficient early.',
        linkedFeature: '/my-estate-trust-strategy?tab=gifting',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Update beneficiary designations for new brokerage accounts',
        description: 'Vested shares held in new or expanded accounts need explicit beneficiary designations or trust titling.',
        linkedFeature: '/titling',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Review estate plan for new asset level',
        description: 'Plans written before rapid wealth accumulation may have inadequate trust structures, outdated distribution provisions, or missing strategies.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'rv1',
        question: 'Have you modeled your estate tax exposure at the new asset level?',
        options: [
          { label: 'Yes — estate tax snapshot is current', score: 3 },
          { label: 'Rough idea but not formally modeled', score: 2 },
          { label: 'No — haven\'t looked at estate tax yet', score: 0, hint: 'A large vest can cross thresholds you weren\'t previously near' },
          { label: 'Below any estate tax threshold', score: 3 },
        ],
      },
      {
        id: 'rv2',
        question: 'Do you have a strategy for your concentrated employer stock position?',
        options: [
          { label: 'Yes — diversification plan with an advisor', score: 3 },
          { label: 'Planning to diversify but no formal plan', score: 2 },
          { label: 'Holding it all — intend to sell later', score: 1, hint: 'Concentration risk compounds estate planning complexity' },
          { label: 'No position or already diversified', score: 3 },
        ],
      },
      {
        id: 'rv3',
        question: 'Have you used any of the post-vest window for gifting strategies?',
        options: [
          { label: 'Yes — annual exclusion gifts or trust funding', score: 3 },
          { label: 'Aware of the opportunity, haven\'t acted', score: 2 },
          { label: 'No — didn\'t know this was a strategy', score: 0 },
          { label: 'Estate below gifting threshold', score: 3 },
        ],
      },
      {
        id: 'rv4',
        question: 'Are beneficiary designations current on brokerage accounts holding vested shares?',
        options: [
          { label: 'Yes — all reviewed and current', score: 3 },
          { label: 'Some updated, others pending', score: 2 },
          { label: 'No — accounts are relatively new', score: 0 },
          { label: 'Assets held in a trust', score: 3 },
        ],
      },
      {
        id: 'rv5',
        question: 'Has your estate attorney reviewed your plan at the current asset level?',
        options: [
          { label: 'Yes — reviewed recently', score: 3 },
          { label: 'Haven\'t updated since wealth grew', score: 1 },
          { label: 'No estate attorney', score: 0 },
          { label: 'Scheduled for review', score: 2 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'RSU Vest and Liquidity Events: Estate Planning Guide for Executives',
    seoDescription: 'Estate tax exposure, concentrated stock strategy, gifting windows, and beneficiary updates after a large RSU vest or liquidity event.',
    relatedSlugs: ['selling-a-business', 'approaching-retirement'],
  },

  'new-child-grandchild': {
    slug: 'new-child-grandchild',
    title: 'New Child or Grandchild',
    shortTitle: 'New Child / Grandchild',
    category: 'family',
    urgency: 'moderate',
    heroLine: 'A new child or grandchild changes who your estate goes to — and who raises them if something happens to you.',
    subhead: 'Guardian designations, trust provisions for minors, and beneficiary updates must be executed after every new family member. Most parents intend to get around to it. Many don\'t.',
    whatChanges: [
      'Existing will may not include new children or grandchildren as beneficiaries',
      'Guardian designation is invalid or absent without a current, valid will',
      'Trusts for minors should specify age of distribution and trustee powers',
      'New 529 accounts and custodial accounts need beneficiary designations',
      'Life insurance coverage should be reviewed for adequacy given new dependents',
    ],
    actions: [
      {
        priority: 1,
        title: 'Update your will to name a guardian',
        description: 'Without a named guardian in a valid will, a court decides who raises your child. This is the most important legal step for parents of minors.',
        professionalType: 'attorney',
        urgencyDays: 60,
      },
      {
        priority: 1,
        title: 'Add the new family member to your estate plan',
        description: 'Explicitly include new children and grandchildren in trust distributions and will provisions. Don\'t assume they\'re automatically included.',
        professionalType: 'attorney',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Review life insurance adequacy',
        description: 'New dependents increase income replacement needs. Review both coverage amount and beneficiary designations.',
        linkedFeature: '/insurance',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Open and designate a 529 account',
        description: '529 contributions up to $18,000 per year ($36,000 for couples) qualify for annual gift tax exclusion. Superfunding allows 5-year front-loading.',
        urgencyDays: 180,
      },
      {
        priority: 3,
        title: 'Update all beneficiary designations',
        description: 'Add the new family member as a contingent or conditional beneficiary where appropriate. Minor children cannot directly receive life insurance proceeds — a trust is required.',
        linkedFeature: '/titling',
      },
    ],
    assessmentQuestions: [
      {
        id: 'nc1',
        question: 'Does your will name a guardian for minor children?',
        options: [
          { label: 'Yes — current will with named guardian', score: 3 },
          { label: 'Will exists but guardian may not be named or current', score: 1 },
          { label: 'No will', score: 0, hint: 'Without a will, a court decides who raises your children' },
          { label: 'No minor children', score: 3 },
        ],
      },
      {
        id: 'nc2',
        question: 'Is the new child or grandchild named in your estate documents?',
        options: [
          { label: 'Yes — documents updated after the birth/adoption', score: 3 },
          { label: 'Not yet — intend to update soon', score: 1 },
          { label: 'No — didn\'t know I needed to', score: 0, hint: 'Children born after a will is signed may not be automatically included' },
          { label: 'No estate documents to update', score: 0 },
        ],
      },
      {
        id: 'nc3',
        question: 'Has life insurance coverage been reviewed for the new dependent?',
        options: [
          { label: 'Yes — coverage reviewed and updated', score: 3 },
          { label: 'Existing coverage — haven\'t reviewed since the birth', score: 2 },
          { label: 'No life insurance', score: 0, hint: 'New dependents significantly increase income replacement needs' },
          { label: 'Covered through employer — will review', score: 2 },
        ],
      },
      {
        id: 'nc4',
        question: 'Have you opened or updated 529 or custodial accounts?',
        options: [
          { label: 'Yes — account opened and funded', score: 3 },
          { label: 'Planning to — haven\'t yet', score: 2 },
          { label: 'No — not a priority right now', score: 1 },
          { label: 'Not applicable — grandchild already has accounts', score: 3 },
        ],
      },
      {
        id: 'nc5',
        question: 'Do your beneficiary designations account for the new family member appropriately?',
        options: [
          { label: 'Yes — all reviewed and updated', score: 3 },
          { label: 'Partial — some updated', score: 2 },
          { label: 'No — still have old designations', score: 0 },
          { label: 'Unsure what they say', score: 0 },
        ],
      },
    ],
    advisorCTA: false,
    attorneyCTA: true,
    seoTitle: 'New Child or Grandchild: Estate Planning Checklist',
    seoDescription: 'Guardian designations, trust provisions for minors, beneficiary updates, and 529 accounts after a new child or grandchild.',
    relatedSlugs: ['serious-diagnosis', 'approaching-retirement'],
  },

  ...EVENT_CONTENT_SPRINT5,
}

export const EVENT_SLUGS = Object.keys(EVENT_CONTENT)

export function getEventContent(slug: string): EventContent | null {
  return EVENT_CONTENT[slug] ?? null
}
