import type { EventContent } from './types'

export const EVENT_CONTENT_SPRINT5: Record<string, EventContent> = {
  'getting-married': {
    slug: 'getting-married',
    title: 'Getting Married',
    shortTitle: 'Getting Married',
    category: 'family',
    urgency: 'high',
    heroLine: 'Marriage merges two financial lives — and creates planning obligations most couples don\'t address until it\'s too late.',
    subhead: 'Beneficiary designations, titling, powers of attorney, and estate documents all need to reflect your new legal status. At the $2M–$30M level, the interaction between premarital assets, prenuptial agreements, and estate tax planning adds significant complexity.',
    whatChanges: [
      'All existing beneficiary designations remain unchanged — your new spouse is not automatically added',
      'Premarital assets may or may not be subject to marital property laws depending on your state and titling',
      'Existing wills and trusts do not automatically update to include a new spouse in most states',
      'Powers of attorney and healthcare directives should name your spouse if that is your intent',
      'Joint titling decisions made now affect estate tax planning, probate exposure, and divorce outcomes for decades',
    ],
    actions: [
      {
        priority: 1,
        title: 'Update all beneficiary designations',
        description: 'Every retirement account, life insurance policy, and financial account must be updated individually. Your spouse is not automatically added.',
        linkedFeature: '/titling',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Execute new powers of attorney and healthcare directives',
        description: 'Name your spouse as your agent if that is your intent. Existing documents may still name an ex-partner or parent.',
        professionalType: 'attorney',
        urgencyDays: 60,
        linkedFeature: '/incapacity-planning',
      },
      {
        priority: 2,
        title: 'Review and update your will and trust documents',
        description: 'Your existing estate plan was written for a different situation. It needs to reflect your new household, including any children from prior relationships.',
        professionalType: 'attorney',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Decide on titling strategy for premarital and new assets',
        description: 'Separate vs joint titling has long-term implications for estate tax, divorce protection, and probate. This decision deserves professional guidance.',
        professionalType: 'attorney',
        urgencyDays: 90,
        linkedFeature: '/titling',
      },
      {
        priority: 3,
        title: 'Model your combined household estate picture',
        description: 'Two estates merging may create new federal or state estate tax exposure. Run a fresh estate tax snapshot for the combined household.',
        linkedFeature: '/estate-tax',
      },
    ],
    assessmentQuestions: [
      {
        id: 'gm1',
        question: 'Have you updated beneficiary designations on all accounts to reflect your new spouse?',
        options: [
          { label: 'Yes — all updated after the wedding', score: 3 },
          { label: 'Some updated, others pending', score: 1 },
          { label: 'Not yet — planning to', score: 0, hint: 'Your spouse is not automatically added to any account' },
          { label: 'Not married yet — planning ahead', score: 2 },
        ],
      },
      {
        id: 'gm2',
        question: 'Have you executed new powers of attorney naming your spouse?',
        options: [
          { label: 'Yes — new documents signed', score: 3 },
          { label: 'In process with an attorney', score: 2 },
          { label: 'No — old documents still in place', score: 0, hint: 'Your old POA may name someone you no longer intend' },
          { label: 'Never had these documents', score: 1 },
        ],
      },
      {
        id: 'gm3',
        question: 'Have your will and trust documents been updated for your new marriage?',
        options: [
          { label: 'Yes — reviewed and updated', score: 3 },
          { label: 'Scheduled with an attorney', score: 2 },
          { label: 'Not yet', score: 0 },
          { label: 'No estate documents to update', score: 0 },
        ],
      },
      {
        id: 'gm4',
        question: 'Have you decided how premarital assets will be titled going forward?',
        options: [
          { label: 'Yes — reviewed with an attorney', score: 3 },
          { label: 'General understanding but no formal review', score: 2 },
          { label: 'No — haven\'t thought about it', score: 0, hint: 'Titling decisions made now are hard to undo' },
          { label: 'Prenuptial agreement addresses this', score: 3 },
        ],
      },
      {
        id: 'gm5',
        question: 'Have you modeled the combined household estate tax picture?',
        options: [
          { label: 'Yes — updated estate tax snapshot', score: 3 },
          { label: 'Rough idea but not formally modeled', score: 2 },
          { label: 'No — not yet a priority', score: 1 },
          { label: 'Below estate tax threshold', score: 3 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Getting Married: Estate Planning Guide for $2M–$30M Households',
    seoDescription: 'What to update when you get married — beneficiary designations, powers of attorney, titling, and estate documents. The planning checklist for high-net-worth couples.',
    relatedSlugs: ['divorce', 'new-child-grandchild'],
  },

  'remarriage-blended-family': {
    slug: 'remarriage-blended-family',
    title: 'Remarriage and Blended Family',
    shortTitle: 'Remarriage / Blended Family',
    category: 'family',
    urgency: 'critical',
    heroLine: 'Remarriage with children from a prior relationship is one of the most legally complex estate planning situations that exists.',
    subhead: 'Without careful planning, assets intended for your children may pass entirely to a new spouse — and vice versa. Trusts, prenuptial agreements, and beneficiary coordination are essential, not optional, at the $2M–$30M level.',
    whatChanges: [
      'Intestate succession laws may give your new spouse rights to assets you intended for your children',
      'A surviving spouse can potentially disinherit stepchildren by changing beneficiary designations after your death',
      'QTIP trusts and other marital trust structures can provide for a spouse while protecting children\'s inheritance',
      'Children from a prior marriage may have legal rights to elective share in some states regardless of your will',
      'Life insurance and retirement account beneficiary designations control asset flow — not your will',
    ],
    actions: [
      {
        priority: 1,
        title: 'Review and restructure your estate plan before or immediately after remarriage',
        description: 'A will or trust written for a prior marriage is almost certainly wrong for your current situation. This is not optional.',
        professionalType: 'attorney',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Consider a QTIP trust or other marital trust structure',
        description: 'These trusts provide income to a surviving spouse while preserving principal for children from a prior relationship.',
        professionalType: 'attorney',
        urgencyDays: 60,
        linkedFeature: '/my-estate-trust-strategy?tab=trusts',
      },
      {
        priority: 1,
        title: 'Update all beneficiary designations intentionally',
        description: 'Decide explicitly who receives each account. Do not let default designations make this decision for you.',
        linkedFeature: '/titling',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Consider a prenuptial agreement if not already in place',
        description: 'A prenuptial agreement is the cleanest way to establish clear expectations for asset division and inheritance.',
        professionalType: 'attorney',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Have a direct conversation with all children about your intentions',
        description: 'Blended family estate disputes are among the most common and damaging. A clear family conversation reduces the risk of litigation.',
      },
    ],
    assessmentQuestions: [
      {
        id: 'rb1',
        question: 'Has your estate plan been updated to reflect your blended family structure?',
        options: [
          { label: 'Yes — reviewed with an attorney for blended family specifically', score: 3 },
          { label: 'Updated but not specifically for blended family complexity', score: 1 },
          { label: 'No — using documents from prior marriage', score: 0, hint: 'Prior marriage documents are almost certainly wrong for this situation' },
          { label: 'No estate documents', score: 0 },
        ],
      },
      {
        id: 'rb2',
        question: 'Have beneficiary designations been reviewed with your blended family in mind?',
        options: [
          { label: 'Yes — intentionally assigned to protect all children', score: 3 },
          { label: 'Some reviewed, others default', score: 1 },
          { label: 'No — haven\'t addressed this', score: 0 },
          { label: 'All assets in trust — designations coordinated', score: 3 },
        ],
      },
      {
        id: 'rb3',
        question: 'Do you have a trust structure that provides for your spouse while protecting children\'s inheritance?',
        options: [
          { label: 'Yes — QTIP or similar structure in place', score: 3 },
          { label: 'Discussed with attorney but not yet implemented', score: 2 },
          { label: 'No — not aware this was needed', score: 0, hint: 'Without this, a surviving spouse can potentially disinherit your children' },
          { label: 'No spouse or no children from prior relationship', score: 3 },
        ],
      },
      {
        id: 'rb4',
        question: 'Is there a prenuptial agreement addressing asset division and inheritance?',
        options: [
          { label: 'Yes — prenuptial in place', score: 3 },
          { label: 'Not married yet — considering it', score: 2 },
          { label: 'No prenuptial agreement', score: 1 },
          { label: 'Already remarried — postnuptial being considered', score: 2 },
        ],
      },
      {
        id: 'rb5',
        question: 'Have you communicated your estate intentions clearly to all children?',
        options: [
          { label: 'Yes — explicit conversations have happened', score: 3 },
          { label: 'General understanding but no formal conversation', score: 2 },
          { label: 'No — it feels uncomfortable', score: 1, hint: 'Undisclosed intentions are a leading cause of estate litigation' },
          { label: 'Children are minors — not yet applicable', score: 2 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Remarriage and Blended Family: Estate Planning Guide',
    seoDescription: 'How to protect children from a prior marriage while providing for a new spouse. QTIP trusts, beneficiary coordination, and prenuptial agreements for blended families.',
    relatedSlugs: ['getting-married', 'divorce', 'new-child-grandchild'],
  },

  'aging-parent-needs-care': {
    slug: 'aging-parent-needs-care',
    title: 'Aging Parent Needs Care',
    shortTitle: 'Aging Parent Care',
    category: 'family',
    urgency: 'high',
    heroLine: 'When a parent needs care, their estate plan — and yours — both need immediate attention.',
    subhead: 'Decisions made in the first weeks of a parent\'s care need often have permanent financial and legal consequences. Medicaid planning, POA authority, and family coordination must happen before capacity is lost.',
    whatChanges: [
      'A parent without a current POA may require court-appointed guardianship — a lengthy and expensive process',
      'Medicaid eligibility has a 5-year look-back period — gifting assets to qualify has strict rules',
      'Assets inherited from a parent may significantly change your own estate tax exposure',
      'Caregiving responsibilities may affect your own income, retirement savings, and estate plan',
      'Sibling disagreements over care decisions are among the most common family disputes — a clear POA prevents them',
    ],
    actions: [
      {
        priority: 1,
        title: 'Confirm your parent has current POA and healthcare directive',
        description: 'If they don\'t, and capacity is lost, court guardianship is the only alternative. This must happen while they can legally sign.',
        professionalType: 'attorney',
        urgencyDays: 14,
      },
      {
        priority: 1,
        title: 'Understand Medicaid planning options if long-term care is likely',
        description: 'Medicaid has a 5-year look-back on asset transfers. Planning must start well before it\'s needed.',
        professionalType: 'attorney',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Inventory your parent\'s assets and estate documents',
        description: 'Knowing what exists — and where — prevents assets from being lost or inaccessible during a crisis.',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Update your own estate plan to account for a potential inheritance',
        description: 'An inheritance from a parent may push your estate into new tax territory. Model the impact now.',
        linkedFeature: '/estate-tax',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Review your own incapacity planning',
        description: 'Watching a parent navigate care without documents is a powerful reminder to complete your own.',
        linkedFeature: '/incapacity-planning',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'ap1',
        question: 'Does your parent have a current Durable Power of Attorney?',
        options: [
          { label: 'Yes — current and accessible', score: 3 },
          { label: 'Exists but may be outdated', score: 1 },
          { label: 'No — this is urgent', score: 0, hint: 'Without POA, court guardianship may be the only option' },
          { label: 'Unsure', score: 0 },
        ],
      },
      {
        id: 'ap2',
        question: 'Have you considered Medicaid planning if long-term care is likely?',
        options: [
          { label: 'Yes — working with an elder law attorney', score: 3 },
          { label: 'Aware of it but haven\'t acted', score: 1, hint: '5-year look-back means planning must start early' },
          { label: 'No — not sure it applies', score: 0 },
          { label: 'Long-term care insurance covers this', score: 3 },
        ],
      },
      {
        id: 'ap3',
        question: 'Have you inventoried your parent\'s assets and located their estate documents?',
        options: [
          { label: 'Yes — fully documented', score: 3 },
          { label: 'Partial — know some but not all', score: 2 },
          { label: 'No — haven\'t started', score: 0 },
          { label: 'Parent handles their own affairs independently', score: 3 },
        ],
      },
      {
        id: 'ap4',
        question: 'Have you modeled how a potential inheritance might affect your own estate?',
        options: [
          { label: 'Yes — updated my estate tax picture', score: 3 },
          { label: 'Roughly estimated but not formally', score: 2 },
          { label: 'No — hadn\'t thought about it', score: 1 },
          { label: 'Inheritance unlikely or below threshold', score: 3 },
        ],
      },
      {
        id: 'ap5',
        question: 'Is your own incapacity planning (POA, healthcare directive) current?',
        options: [
          { label: 'Yes — reviewed recently', score: 3 },
          { label: 'Exists but not recently reviewed', score: 2 },
          { label: 'No — this situation is motivating me to act', score: 1 },
          { label: 'No documents', score: 0 },
        ],
      },
    ],
    advisorCTA: false,
    attorneyCTA: true,
    seoTitle: 'Aging Parent Needs Care: Estate Planning Checklist',
    seoDescription: 'POA, Medicaid planning, and estate coordination when a parent needs care. What to do immediately and what to plan for.',
    relatedSlugs: ['serious-diagnosis', 'receiving-inheritance'],
  },

  'loss-of-parent': {
    slug: 'loss-of-parent',
    title: 'Loss of a Parent',
    shortTitle: 'Loss of Parent',
    category: 'family',
    urgency: 'high',
    heroLine: 'Losing a parent often triggers an inheritance — and the planning obligations that come with it.',
    subhead: 'An inheritance can push a household into new estate tax territory, require immediate beneficiary updates, and create inherited IRA distribution obligations with significant tax implications. These decisions have deadlines.',
    whatChanges: [
      'Inherited IRAs require distribution within 10 years — the annual RMD rules within that window depend on when the owner died',
      'Stepped-up basis on inherited non-retirement assets resets capital gains — a significant tax benefit if used correctly',
      'Assets inherited outside of probate (beneficiary designations, joint tenancy) need new beneficiary designations immediately',
      'Your gross estate may now exceed federal or state estate tax thresholds for the first time',
      'As the executor or trustee, you have legal fiduciary obligations with specific deadlines',
    ],
    actions: [
      {
        priority: 1,
        title: 'Understand your inherited IRA distribution obligations',
        description: 'Non-spouse beneficiaries must distribute within 10 years. Annual RMD requirements within that window depend on whether the original owner was already taking RMDs.',
        professionalType: 'cpa',
        urgencyDays: 30,
        linkedFeature: '/rmd',
      },
      {
        priority: 1,
        title: 'Inventory and retitle inherited assets',
        description: 'Assets passing outside probate (beneficiary designations, joint tenancy) transfer automatically but need new beneficiary designations in your name.',
        linkedFeature: '/titling',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Calculate your updated gross estate',
        description: 'Add inherited assets to your existing estate and run a fresh estate tax snapshot. You may have crossed a threshold that changes your planning priorities.',
        linkedFeature: '/estate-tax',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Use the stepped-up basis on inherited assets strategically',
        description: 'Non-retirement inherited assets receive a basis reset to date-of-death value. Selling timing and asset selection have significant capital gains implications.',
        professionalType: 'cpa',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Update your own estate plan to reflect the new asset level',
        description: 'Your existing estate plan was written for a different asset level. Review and update distribution provisions, trust structures, and strategies.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'lp1',
        question: 'Do you understand the distribution rules for any inherited retirement accounts?',
        options: [
          { label: 'Yes — reviewed with a CPA or advisor', score: 3 },
          { label: 'Generally — know the 10-year rule', score: 2 },
          { label: 'No — this is new to me', score: 0, hint: 'Mistakes here are irreversible and costly' },
          { label: 'No inherited retirement accounts', score: 3 },
        ],
      },
      {
        id: 'lp2',
        question: 'Have you retitled inherited assets and added new beneficiary designations?',
        options: [
          { label: 'Yes — all retitled and updated', score: 3 },
          { label: 'In process', score: 2 },
          { label: 'Not yet started', score: 0 },
          { label: 'Assets passing through probate — in process', score: 2 },
        ],
      },
      {
        id: 'lp3',
        question: 'Have you calculated your updated estate tax exposure including inherited assets?',
        options: [
          { label: 'Yes — updated estate tax snapshot', score: 3 },
          { label: 'Rough estimate only', score: 2 },
          { label: 'No', score: 0 },
          { label: 'Below estate tax thresholds', score: 3 },
        ],
      },
      {
        id: 'lp4',
        question: 'Have you consulted a CPA about the stepped-up basis on inherited assets?',
        options: [
          { label: 'Yes — tax strategy in place', score: 3 },
          { label: 'Aware of stepped-up basis but haven\'t planned around it', score: 2 },
          { label: 'No — not familiar with this', score: 0, hint: 'Basis reset can save significant capital gains taxes' },
          { label: 'No non-retirement inherited assets', score: 3 },
        ],
      },
      {
        id: 'lp5',
        question: 'Has your own estate plan been reviewed at the new asset level?',
        options: [
          { label: 'Yes — updated', score: 3 },
          { label: 'Scheduled', score: 2 },
          { label: 'Not yet', score: 1 },
          { label: 'No estate plan', score: 0 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Loss of a Parent: Estate Planning Checklist for Beneficiaries',
    seoDescription: 'Inherited IRA rules, stepped-up basis, estate tax exposure, and beneficiary updates after losing a parent. What to do and when.',
    relatedSlugs: ['receiving-inheritance', 'aging-parent-needs-care'],
  },

  'starting-a-business': {
    slug: 'starting-a-business',
    title: 'Starting a Business',
    shortTitle: 'Starting a Business',
    category: 'business',
    urgency: 'high',
    heroLine: 'A new business changes your estate plan, your liability exposure, and your tax picture from day one.',
    subhead: 'Entity structure, buy-sell agreements, and personal liability protection must be addressed at formation — not after the business has value. At the $2M–$30M level, a new business is often the largest asset added to an already complex estate.',
    whatChanges: [
      'Personal liability exposure depends entirely on entity structure — sole proprietors have none of the protection LLCs provide',
      'A buy-sell agreement funded by life insurance must be in place before partners disagree or die',
      'Business interests are difficult to value, illiquid, and create estate planning complexity not present with financial assets',
      'Operating agreements and shareholder agreements govern what happens to your interest if you die or become incapacitated',
      'Self-employment income affects Social Security benefit calculations and retirement account contribution limits',
    ],
    actions: [
      {
        priority: 1,
        title: 'Confirm entity structure with an attorney',
        description: 'LLC, S-Corp, C-Corp, and partnership structures have different liability, tax, and estate planning implications. The choice made at formation is difficult to change.',
        professionalType: 'attorney',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Execute a buy-sell agreement if there are partners',
        description: 'A buy-sell agreement funded by life insurance ensures business continuity if a partner dies, becomes incapacitated, or wants to exit.',
        professionalType: 'attorney',
        urgencyDays: 60,
        linkedFeature: '/businesses',
      },
      {
        priority: 2,
        title: 'Add the business to your estate plan',
        description: 'Who inherits your business interest? Can they actually operate or sell it? Your estate plan must address these questions explicitly.',
        professionalType: 'attorney',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Review personal liability insurance coverage',
        description: 'Entity structure limits but does not eliminate personal liability. Umbrella policies and professional liability coverage fill critical gaps.',
        linkedFeature: '/insurance',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Model the business\'s impact on your estate tax picture',
        description: 'Even a modest new business adds illiquid value to your gross estate. Model the impact on your estate tax exposure.',
        linkedFeature: '/estate-tax',
      },
    ],
    assessmentQuestions: [
      {
        id: 'sb1',
        question: 'Has your entity structure been reviewed by an attorney for liability and estate planning implications?',
        options: [
          { label: 'Yes — structure chosen with professional guidance', score: 3 },
          { label: 'Formed an LLC but not reviewed for estate planning', score: 2 },
          { label: 'Operating as sole proprietor', score: 0, hint: 'Sole proprietors have no liability protection' },
          { label: 'In process of forming', score: 2 },
        ],
      },
      {
        id: 'sb2',
        question: 'If you have business partners, is there a buy-sell agreement in place?',
        options: [
          { label: 'Yes — funded by life insurance', score: 3 },
          { label: 'Agreement exists but not funded', score: 1 },
          { label: 'No buy-sell agreement', score: 0, hint: 'Partner death without a buy-sell agreement creates serious problems' },
          { label: 'No business partners', score: 3 },
        ],
      },
      {
        id: 'sb3',
        question: 'Does your estate plan address what happens to your business interest if you die?',
        options: [
          { label: 'Yes — explicitly addressed', score: 3 },
          { label: 'Will exists but doesn\'t specifically address the business', score: 1 },
          { label: 'No estate plan', score: 0 },
          { label: 'Business is in a trust', score: 3 },
        ],
      },
      {
        id: 'sb4',
        question: 'Have you reviewed your personal liability insurance given the new business?',
        options: [
          { label: 'Yes — umbrella and professional liability in place', score: 3 },
          { label: 'Basic coverage but not reviewed since starting the business', score: 2 },
          { label: 'No review', score: 0 },
          { label: 'Entity structure provides adequate protection', score: 2 },
        ],
      },
      {
        id: 'sb5',
        question: 'Have you modeled the business\'s impact on your estate tax exposure?',
        options: [
          { label: 'Yes — estate tax snapshot updated', score: 3 },
          { label: 'Rough idea but not formally modeled', score: 2 },
          { label: 'No', score: 1 },
          { label: 'Business value is minimal at this stage', score: 2 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Starting a Business: Estate Planning Guide for Founders',
    seoDescription: 'Entity structure, buy-sell agreements, and estate planning for new business owners at the $2M–$30M level.',
    relatedSlugs: ['selling-a-business', 'large-rsu-vest'],
  },

  'selling-a-home': {
    slug: 'selling-a-home',
    title: 'Selling a Home',
    shortTitle: 'Selling a Home',
    category: 'wealth',
    urgency: 'moderate',
    heroLine: 'A home sale at the $2M–$30M level often generates significant taxable gain and changes your estate picture materially.',
    subhead: 'The $500K primary residence exclusion is the most misunderstood rule in real estate taxation. Vacation homes, rental properties, and properties held in trust have different treatment. The decisions made before closing affect taxes for years.',
    whatChanges: [
      'Primary residence exclusion ($250K single / $500K married) applies only with 2-year ownership and use — rental periods reduce eligibility',
      'Gain above the exclusion is taxable as long-term capital gain plus possible NIIT at higher income levels',
      'Proceeds added to your liquid estate may push your gross estate closer to or above estate tax thresholds',
      'If the home was in a trust, the trust structure affects how gain is taxed and how proceeds are distributed',
      'A 1031 exchange for investment properties can defer gain — but has strict identification and closing deadlines',
    ],
    actions: [
      {
        priority: 1,
        title: 'Calculate your expected taxable gain before closing',
        description: 'Determine your adjusted basis, eligibility for the primary residence exclusion, and estimated federal and state capital gains tax.',
        professionalType: 'cpa',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Consider a 1031 exchange if this is an investment property',
        description: '45 days to identify a replacement property, 180 days to close. The clock starts at sale. Planning must happen before closing.',
        professionalType: 'cpa',
        urgencyDays: 14,
      },
      {
        priority: 2,
        title: 'Model the impact of proceeds on your estate tax picture',
        description: 'Liquid proceeds from a home sale increase your gross estate. Run an updated estate tax snapshot with the expected net proceeds.',
        linkedFeature: '/estate-tax',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Update titling and beneficiary designations for new accounts',
        description: 'Proceeds deposited into new or existing accounts need current beneficiary designations and appropriate titling.',
        linkedFeature: '/titling',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Review your overall real estate allocation',
        description: 'After a sale, model your updated real estate vs financial asset allocation and whether it still reflects your plan.',
        linkedFeature: '/real-estate',
      },
    ],
    assessmentQuestions: [
      {
        id: 'sh1',
        question: 'Have you calculated your expected taxable gain and tax liability from the sale?',
        options: [
          { label: 'Yes — reviewed with a CPA', score: 3 },
          { label: 'Rough estimate based on my own research', score: 2 },
          { label: 'No — planning to figure it out after closing', score: 0, hint: 'Tax planning is most effective before the sale closes' },
          { label: 'Gain is below the exclusion threshold', score: 3 },
        ],
      },
      {
        id: 'sh2',
        question: 'If this is an investment property, have you evaluated a 1031 exchange?',
        options: [
          { label: 'Yes — 1031 exchange is in process', score: 3 },
          { label: 'Considered it but decided against', score: 3 },
          { label: 'Not aware of the option', score: 0, hint: '45-day identification window starts at closing' },
          { label: 'Primary residence — not applicable', score: 3 },
        ],
      },
      {
        id: 'sh3',
        question: 'Have you modeled how the sale proceeds affect your estate tax picture?',
        options: [
          { label: 'Yes — updated estate tax snapshot', score: 3 },
          { label: 'Roughly estimated', score: 2 },
          { label: 'No', score: 1 },
          { label: 'Proceeds stay below estate tax threshold', score: 3 },
        ],
      },
      {
        id: 'sh4',
        question: 'Will the proceeds go into accounts with current beneficiary designations?',
        options: [
          { label: 'Yes — all accounts reviewed and current', score: 3 },
          { label: 'Some accounts updated', score: 2 },
          { label: 'No — haven\'t addressed this', score: 0 },
          { label: 'Proceeds going into a trust', score: 3 },
        ],
      },
      {
        id: 'sh5',
        question: 'Have you reviewed your overall real estate and asset allocation after the sale?',
        options: [
          { label: 'Yes — allocation reviewed with an advisor', score: 3 },
          { label: 'General sense but not formally reviewed', score: 2 },
          { label: 'No', score: 1 },
          { label: 'Real estate was a small part of my portfolio', score: 2 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: false,
    seoTitle: 'Selling a Home: Estate Planning and Tax Guide for $2M–$30M Households',
    seoDescription: 'Capital gains exclusion, 1031 exchanges, estate tax impact, and beneficiary updates when selling a home at the $2M–$30M level.',
    relatedSlugs: ['receiving-inheritance', 'large-rsu-vest'],
  },

  'multi-state-real-estate': {
    slug: 'multi-state-real-estate',
    title: 'Multi-State Real Estate',
    shortTitle: 'Multi-State Real Estate',
    category: 'wealth',
    urgency: 'high',
    heroLine: 'Owning real estate in multiple states means multiple probate proceedings — unless you plan around it.',
    subhead: 'Each state where you own real property at death requires its own probate proceeding. For a $2M–$30M household with vacation homes, rental properties, or commercial real estate across state lines, this means multiple attorneys, multiple courts, and years of delay for your heirs.',
    whatChanges: [
      'Probate is required in each state where you own real property at death — not just your state of domicile',
      'Each state has different estate tax rules — some states have exemptions as low as $1M',
      'Titling property in a revocable trust avoids ancillary probate entirely',
      'LLC ownership of investment properties provides liability protection and simplifies estate transfer',
      'State income tax residency rules can be triggered by the amount of time spent at a vacation property',
    ],
    actions: [
      {
        priority: 1,
        title: 'Title out-of-state real estate into a revocable trust',
        description: 'Property held in a trust avoids probate in every state. This is the cleanest solution for multi-state real estate exposure.',
        professionalType: 'attorney',
        urgencyDays: 90,
        linkedFeature: '/titling',
      },
      {
        priority: 1,
        title: 'Review state estate tax exposure for each state where you own property',
        description: 'Some states tax non-resident real estate in their state. Massachusetts, Oregon, and Washington all have estate taxes that apply to in-state real property.',
        linkedFeature: '/domicile-analysis',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Consider LLC ownership for investment properties',
        description: 'An LLC provides liability protection and allows you to transfer ownership interests rather than the real property itself — simplifying estate transfer.',
        professionalType: 'attorney',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Review state income tax residency exposure',
        description: 'Spending significant time at an out-of-state property can trigger income tax residency in that state. Know the rules before you cross the threshold.',
        linkedFeature: '/domicile-analysis',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Confirm your intended domicile state is properly established',
        description: 'Your domicile determines which state\'s estate tax applies to your full estate. Document the factors that establish domicile in your intended state.',
        linkedFeature: '/domicile-analysis',
      },
    ],
    assessmentQuestions: [
      {
        id: 'mr1',
        question: 'Is your out-of-state real estate held in a revocable trust?',
        options: [
          { label: 'Yes — all out-of-state property in trust', score: 3 },
          { label: 'Some in trust, some in personal name', score: 1, hint: 'Personal-name property requires probate in each state' },
          { label: 'No — all in personal name', score: 0, hint: 'Ancillary probate required in each state at death' },
          { label: 'Only own real estate in one state', score: 3 },
        ],
      },
      {
        id: 'mr2',
        question: 'Have you reviewed state estate tax exposure for each state where you own property?',
        options: [
          { label: 'Yes — reviewed with an attorney', score: 3 },
          { label: 'Aware of the issue but not formally reviewed', score: 2 },
          { label: 'No — didn\'t know this was a concern', score: 0, hint: 'Some states tax non-resident real estate' },
          { label: 'All property in no-estate-tax states', score: 3 },
        ],
      },
      {
        id: 'mr3',
        question: 'Are investment properties held in LLCs?',
        options: [
          { label: 'Yes — all investment properties in LLCs', score: 3 },
          { label: 'Some in LLCs, some personal', score: 2 },
          { label: 'No LLCs — all personal name', score: 0 },
          { label: 'Only primary residence — not applicable', score: 3 },
        ],
      },
      {
        id: 'mr4',
        question: 'Have you reviewed state income tax residency rules for time spent at out-of-state properties?',
        options: [
          { label: 'Yes — days tracked and rules known', score: 3 },
          { label: 'Generally aware but not formally tracked', score: 2 },
          { label: 'No — didn\'t know this was an issue', score: 0, hint: 'Some states can claim residency based on days present' },
          { label: 'Not spending significant time in other states', score: 3 },
        ],
      },
      {
        id: 'mr5',
        question: 'Is your intended domicile state clearly established with documentation?',
        options: [
          { label: 'Yes — domicile well-documented', score: 3 },
          { label: 'Believe so but haven\'t formally documented', score: 2 },
          { label: 'Unclear — split time between states', score: 0, hint: 'Unclear domicile is one of the most litigated estate issues' },
          { label: 'Only live in one state', score: 3 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Multi-State Real Estate: Estate Planning Guide',
    seoDescription: 'How to avoid ancillary probate, manage state estate tax exposure, and use trusts and LLCs for multi-state real estate holdings.',
    relatedSlugs: ['selling-a-home', 'selling-a-business'],
  },

  'child-reaching-adulthood': {
    slug: 'child-reaching-adulthood',
    title: 'Child Reaching Adulthood',
    shortTitle: 'Child Reaching Adulthood',
    category: 'family',
    urgency: 'moderate',
    heroLine: 'When a child turns 18, they gain full legal capacity — which changes your estate plan in ways most parents miss.',
    subhead: 'At 18, a child can receive an inheritance outright, you lose automatic medical decision-making authority, and any trust provisions written for minors may trigger automatic distribution. At the $2M–$30M level, distributing significant assets to an 18-year-old outright is rarely what parents intend.',
    whatChanges: [
      'Custodial accounts (UGMA/UTMA) become the child\'s outright property at age 18 or 21 depending on state',
      'You no longer have authority to make medical decisions for your adult child without a healthcare proxy',
      'Trust distribution provisions written for "minor children" may trigger automatic distribution at 18',
      'Beneficiary designations naming the child directly now result in outright distribution rather than trust protection',
      'The child should execute their own POA, healthcare directive, and basic estate documents',
    ],
    actions: [
      {
        priority: 1,
        title: 'Have your adult child execute basic estate documents',
        description: 'Your child needs their own POA, healthcare directive, and FERPA release. You have no legal authority over their medical or financial decisions at 18.',
        professionalType: 'attorney',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Review trust distribution provisions for age-milestone triggers',
        description: 'Many trusts distribute to beneficiaries at 18 or 21. If the trust was funded significantly, you may want to extend the distribution age.',
        professionalType: 'attorney',
        urgencyDays: 60,
        linkedFeature: '/my-estate-trust-strategy?tab=trusts',
      },
      {
        priority: 2,
        title: 'Review UGMA/UTMA account balances and timing',
        description: 'These accounts transfer to the child outright at the age of majority. If balances are significant, consider the implications.',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Update beneficiary designations to route through a trust if appropriate',
        description: 'Direct beneficiary designations to an adult child result in outright distribution. A trust as beneficiary adds protection and distribution control.',
        linkedFeature: '/titling',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Review your overall estate distribution plan',
        description: 'An estate plan written when your child was a minor may need significant updates now that they are a legal adult.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'ca1',
        question: 'Has your adult child executed their own POA and healthcare directive?',
        options: [
          { label: 'Yes — documents in place', score: 3 },
          { label: 'In process', score: 2 },
          { label: 'No — hadn\'t thought about it', score: 0, hint: 'You have no legal medical authority over an adult child without these' },
          { label: 'Child is still a minor', score: 3 },
        ],
      },
      {
        id: 'ca2',
        question: 'Have you reviewed trust distribution provisions for age-milestone triggers?',
        options: [
          { label: 'Yes — provisions reviewed and appropriate', score: 3 },
          { label: 'Trust exists but haven\'t reviewed the triggers', score: 1, hint: 'Many trusts distribute outright at 18 or 21' },
          { label: 'No trust', score: 2 },
          { label: 'Trust reviewed and extended distribution age', score: 3 },
        ],
      },
      {
        id: 'ca3',
        question: 'Are UGMA/UTMA accounts sized appropriately for outright transfer at majority?',
        options: [
          { label: 'Yes — amounts are manageable', score: 3 },
          { label: 'Accounts are significant — haven\'t addressed this', score: 0, hint: 'Large custodial accounts transfer outright at 18 or 21' },
          { label: 'No custodial accounts', score: 3 },
          { label: 'Accounts converted to 529 or other structure', score: 3 },
        ],
      },
      {
        id: 'ca4',
        question: 'Are beneficiary designations routing assets through a trust rather than outright to the adult child?',
        options: [
          { label: 'Yes — trust as beneficiary where appropriate', score: 3 },
          { label: 'Some direct, some through trust', score: 2 },
          { label: 'All direct to child', score: 1 },
          { label: 'Haven\'t reviewed since the child was a minor', score: 0 },
        ],
      },
      {
        id: 'ca5',
        question: 'Has your overall estate distribution plan been reviewed since the child became an adult?',
        options: [
          { label: 'Yes — reviewed recently', score: 3 },
          { label: 'Not reviewed since they were a minor', score: 0, hint: 'An estate plan written for a minor is likely wrong for an adult' },
          { label: 'Scheduled for review', score: 2 },
          { label: 'No estate plan', score: 0 },
        ],
      },
    ],
    advisorCTA: false,
    attorneyCTA: true,
    seoTitle: 'Child Reaching Adulthood: Estate Planning Checklist',
    seoDescription: 'What changes when a child turns 18 — custodial accounts, trust distributions, beneficiary designations, and healthcare authority.',
    relatedSlugs: ['new-child-grandchild', 'getting-married'],
  },

  'disability-early-retirement': {
    slug: 'disability-early-retirement',
    title: 'Disability or Early Retirement',
    shortTitle: 'Disability / Early Retirement',
    category: 'health',
    urgency: 'critical',
    heroLine: 'Disability before retirement is one of the most financially devastating events a household can face — and one of the least planned for.',
    subhead: 'Long-term disability eliminates earned income, accelerates asset drawdown, and creates estate planning urgency around incapacity documents and trust funding. The planning decisions made in the first 90 days have decade-long consequences.',
    whatChanges: [
      'Earned income stops — withdrawal sequencing from retirement accounts must begin earlier than planned',
      'Social Security Disability Insurance (SSDI) has a 5-month waiting period and strict eligibility requirements',
      'RMDs may begin sooner than expected if retirement accounts must be tapped early',
      'Incapacity planning documents (POA, healthcare directive) are now urgent rather than precautionary',
      'Life insurance and long-term care insurance coverage adequacy must be reviewed immediately',
    ],
    actions: [
      {
        priority: 1,
        title: 'Confirm incapacity documents are current and accessible',
        description: 'POA and healthcare directive are now in active use territory, not future planning. Confirm they are current, valid, and known to your family.',
        linkedFeature: '/incapacity-planning',
        urgencyDays: 14,
        professionalType: 'attorney',
      },
      {
        priority: 1,
        title: 'Review disability insurance coverage and file claims immediately',
        description: 'Long-term disability has waiting periods. File claims immediately and understand what\'s covered, for how long, and at what percentage of income.',
        linkedFeature: '/insurance',
        urgencyDays: 7,
      },
      {
        priority: 1,
        title: 'Model your updated retirement picture with earlier drawdown',
        description: 'A disability at 50 vs 65 changes the retirement projection entirely. Model withdrawal sequencing with the actual timeline.',
        linkedFeature: '/projections',
        professionalType: 'advisor',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Evaluate SSDI eligibility and application timing',
        description: 'SSDI has a 5-month waiting period — apply immediately. The back-pay provisions are significant but the application process is slow.',
        urgencyDays: 30,
      },
      {
        priority: 3,
        title: 'Update your estate plan for the new situation',
        description: 'An estate plan written for a working, healthy person may need significant revision for a disability scenario.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'de1',
        question: 'Are your POA and healthcare directive current and accessible to your family?',
        options: [
          { label: 'Yes — current and family knows where they are', score: 3 },
          { label: 'Exist but family doesn\'t know where', score: 1, hint: 'Documents your family can\'t find might as well not exist' },
          { label: 'No current documents', score: 0, hint: 'This is the most urgent planning item' },
          { label: 'In process', score: 2 },
        ],
      },
      {
        id: 'de2',
        question: 'Have you filed for all applicable disability benefits?',
        options: [
          { label: 'Yes — all claims filed', score: 3 },
          { label: 'Some filed, others pending', score: 2 },
          { label: 'No — not yet started', score: 0, hint: 'SSDI has a 5-month waiting period — apply immediately' },
          { label: 'Not yet disabled — planning ahead', score: 3 },
        ],
      },
      {
        id: 'de3',
        question: 'Have you modeled your retirement projections with the earlier drawdown timeline?',
        options: [
          { label: 'Yes — updated projections with advisor', score: 3 },
          { label: 'Rough estimate only', score: 2 },
          { label: 'No — overwhelmed by immediate concerns', score: 1, hint: 'Early planning prevents worse outcomes later' },
          { label: 'Planning ahead — not yet disabled', score: 3 },
        ],
      },
      {
        id: 'de4',
        question: 'Is your disability insurance coverage adequate for long-term income replacement?',
        options: [
          { label: 'Yes — long-term disability covers 60%+ of income', score: 3 },
          { label: 'Short-term only or employer coverage only', score: 1, hint: 'Employer coverage often ends at 2 years' },
          { label: 'No disability insurance', score: 0 },
          { label: 'Self-insured — sufficient assets to fund disability period', score: 3 },
        ],
      },
      {
        id: 'de5',
        question: 'Has your estate plan been reviewed for the disability scenario?',
        options: [
          { label: 'Yes — updated for current situation', score: 3 },
          { label: 'Scheduled', score: 2 },
          { label: 'No — focused on immediate needs', score: 1 },
          { label: 'No estate plan', score: 0 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Disability or Early Retirement: Estate Planning and Financial Guide',
    seoDescription: 'What to do financially and legally when facing disability or early retirement. POA, disability insurance, SSDI, and retirement projection updates.',
    relatedSlugs: ['serious-diagnosis', 'approaching-retirement'],
  },

  'estate-tax-law-change': {
    slug: 'estate-tax-law-change',
    title: 'Estate Tax Law Change',
    shortTitle: 'Estate Tax Law Change',
    category: 'wealth',
    urgency: 'critical',
    heroLine: 'The federal estate tax exemption is scheduled to be cut nearly in half at the end of 2025 — affecting millions of households that were previously below the threshold.',
    subhead: 'The Tax Cuts and Jobs Act doubled the federal estate tax exemption in 2018. Without congressional action, it reverts to approximately $7M per person (inflation-adjusted) at the end of 2025. For households in the $7M–$27M range, this creates urgency around gifting, trust strategies, and estate freezes before the window closes.',
    whatChanges: [
      'Federal exemption dropping from ~$13.6M per person to ~$7M per person affects estates previously below threshold',
      'Married couples lose up to $13M of combined exemption if no action is taken before the sunset',
      'Assets gifted before the sunset may be protected even if the exemption drops — use it or lose it',
      'GRATs, SLATs, and other irrevocable trust strategies must be funded before the exemption changes',
      'State estate taxes are unchanged — some states already have exemptions as low as $1M',
    ],
    actions: [
      {
        priority: 1,
        title: 'Calculate your estate tax exposure at the post-sunset exemption level',
        description: 'Model your estate tax liability assuming a ~$7M per person exemption. This is the most important planning number to know right now.',
        linkedFeature: '/estate-tax',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Execute gifting strategies before the exemption sunset',
        description: 'You can use your current higher exemption for gifts now. The IRS has confirmed that gifts made under the higher exemption will not be clawed back.',
        linkedFeature: '/my-estate-trust-strategy?tab=gifting',
        professionalType: 'attorney',
        urgencyDays: 60,
      },
      {
        priority: 1,
        title: 'Fund irrevocable trusts while the higher exemption is available',
        description: 'SLATs, GRATs, and IDGTs funded at the higher exemption level lock in the current rules for those assets.',
        professionalType: 'attorney',
        linkedFeature: '/my-estate-trust-strategy?tab=trusts',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Review spousal portability election strategy',
        description: 'If a spouse has died without a portability election, there may still be time to file. If both spouses are living, confirm your portability plan.',
        professionalType: 'attorney',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Model the impact of the sunset on your estate plan\'s distribution goals',
        description: 'Your estate plan may have been written assuming a higher exemption. Review whether trust structures and distributions still work under the new numbers.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'et1',
        question: 'Have you modeled your estate tax exposure at the post-sunset ~$7M per person exemption?',
        options: [
          { label: 'Yes — modeled and acting on the results', score: 3 },
          { label: 'Aware of the sunset but haven\'t modeled my specific exposure', score: 1, hint: 'The exposure can be surprisingly large for mid-range estates' },
          { label: 'No — not sure it affects me', score: 0, hint: 'If your estate exceeds $7M per person, it likely does' },
          { label: 'Estate is below the post-sunset threshold', score: 3 },
        ],
      },
      {
        id: 'et2',
        question: 'Are you using your current higher exemption for gifts before the potential sunset?',
        options: [
          { label: 'Yes — gifting strategy in place or in motion', score: 3 },
          { label: 'Aware of the opportunity, haven\'t acted', score: 1, hint: 'The window may close — use it or lose it' },
          { label: 'No — not aware this was an option', score: 0 },
          { label: 'Below threshold — not applicable', score: 3 },
        ],
      },
      {
        id: 'et3',
        question: 'Have you funded irrevocable trusts (SLAT, GRAT, IDGT) while the higher exemption is available?',
        options: [
          { label: 'Yes — trusts funded under current exemption', score: 3 },
          { label: 'In discussions with attorney', score: 2 },
          { label: 'No — haven\'t taken action', score: 0 },
          { label: 'Not applicable at my estate level', score: 3 },
        ],
      },
      {
        id: 'et4',
        question: 'Is your estate plan written to work under the lower post-sunset exemption?',
        options: [
          { label: 'Yes — reviewed and updated', score: 3 },
          { label: 'Written under current higher exemption — not reviewed for sunset', score: 0, hint: 'Many plans become suboptimal after the exemption drops' },
          { label: 'Estate below post-sunset threshold', score: 3 },
          { label: 'Scheduled for review', score: 2 },
        ],
      },
      {
        id: 'et5',
        question: 'Have you reviewed spousal portability strategy in the context of the potential sunset?',
        options: [
          { label: 'Yes — portability strategy confirmed', score: 3 },
          { label: 'Single or widowed — portability reviewed separately', score: 2 },
          { label: 'No — not sure what portability means in this context', score: 0 },
          { label: 'Below threshold — not currently relevant', score: 3 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'Estate Tax Law Change: Planning Guide for the 2025 Exemption Sunset',
    seoDescription: 'What the federal estate tax exemption sunset means for $2M–$30M households. Gifting windows, trust strategies, and what to do before the deadline.',
    relatedSlugs: ['selling-a-business', 'large-rsu-vest', 'approaching-retirement'],
  },

  'first-time-high-net-worth': {
    slug: 'first-time-high-net-worth',
    title: 'First-Time High Net Worth',
    shortTitle: 'First-Time $2M+',
    category: 'wealth',
    urgency: 'high',
    heroLine: 'Crossing $2M in net worth for the first time is the moment most people\'s existing planning becomes inadequate.',
    subhead: 'A will, a 401(k), and a life insurance policy may have been sufficient at $500K. At $2M+, estate tax exposure, beneficiary coordination, titling complexity, and professional coordination requirements are categorically different. Most households in this position have planning that was designed for a smaller estate.',
    whatChanges: [
      'Some state estate taxes apply at $1M — you may already be above threshold',
      'A basic will without a trust is often inadequate for efficient wealth transfer at this level',
      'Beneficiary designations become the primary estate planning document — they override your will',
      'Asset protection strategies (trusts, LLCs, umbrella insurance) become relevant at this wealth level',
      'The cost-benefit of working with an estate attorney shifts dramatically in favor of professional planning',
    ],
    actions: [
      {
        priority: 1,
        title: 'Run an estate tax snapshot at your current asset level',
        description: 'Determine whether you have state or federal estate tax exposure today. The answer may surprise you.',
        linkedFeature: '/estate-tax',
        urgencyDays: 14,
      },
      {
        priority: 1,
        title: 'Audit all beneficiary designations',
        description: 'At $2M+, beneficiary designations on retirement accounts and life insurance often control more wealth than your will. Review every one.',
        linkedFeature: '/titling',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Evaluate whether a revocable trust makes sense',
        description: 'A revocable trust avoids probate, provides incapacity protection, and coordinates asset distribution more effectively than a will alone at this wealth level.',
        professionalType: 'attorney',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Review asset protection coverage',
        description: 'Umbrella liability insurance, LLC structures for investment properties, and trust ownership become meaningful at $2M+.',
        linkedFeature: '/insurance',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Connect with an estate planning attorney and financial advisor',
        description: 'At $2M+, the cost of professional estate planning is a rounding error on the assets at risk. The cost of not planning is not.',
        professionalType: 'attorney',
      },
    ],
    assessmentQuestions: [
      {
        id: 'fn1',
        question: 'Do you know whether you have state or federal estate tax exposure at your current asset level?',
        options: [
          { label: 'Yes — modeled and aware of my exposure', score: 3 },
          { label: 'Roughly aware but not formally modeled', score: 2 },
          { label: 'No — haven\'t looked at estate tax yet', score: 0, hint: 'Some states tax estates at $1M — you may already be exposed' },
          { label: 'Below all state and federal thresholds', score: 3 },
        ],
      },
      {
        id: 'fn2',
        question: 'Have beneficiary designations been reviewed on all retirement accounts and life insurance?',
        options: [
          { label: 'Yes — reviewed recently', score: 3 },
          { label: 'Set originally but not reviewed since growing to this level', score: 1, hint: 'Designations set at $200K may be wrong at $2M+' },
          { label: 'No — not sure what they say', score: 0 },
          { label: 'All assets in trust — designations coordinated', score: 3 },
        ],
      },
      {
        id: 'fn3',
        question: 'Do you have a revocable trust or have you evaluated whether one makes sense?',
        options: [
          { label: 'Yes — revocable trust in place', score: 3 },
          { label: 'Evaluated — decided against for now', score: 2 },
          { label: 'No — only a will', score: 1, hint: 'A will alone is often inadequate for efficient transfer at $2M+' },
          { label: 'No estate documents at all', score: 0 },
        ],
      },
      {
        id: 'fn4',
        question: 'Do you have umbrella liability coverage appropriate for your asset level?',
        options: [
          { label: 'Yes — $2M+ umbrella in place', score: 3 },
          { label: 'Some umbrella but not reviewed recently', score: 2 },
          { label: 'No umbrella coverage', score: 0, hint: 'At $2M+, a lawsuit can be catastrophic without an umbrella' },
          { label: 'Assets held in protected structures', score: 3 },
        ],
      },
      {
        id: 'fn5',
        question: 'Do you work with an estate planning attorney and financial advisor?',
        options: [
          { label: 'Yes — both relationships in place', score: 3 },
          { label: 'One but not both', score: 2 },
          { label: 'No professional relationships yet', score: 0, hint: 'At $2M+, professional planning pays for itself many times over' },
          { label: 'Just connected — in onboarding', score: 2 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: 'First-Time High Net Worth: Estate Planning Guide for $2M+ Households',
    seoDescription: 'What changes when you cross $2M in net worth. Estate tax exposure, beneficiary designations, trusts, and professional planning — what you need now.',
    relatedSlugs: ['receiving-inheritance', 'large-rsu-vest', 'selling-a-business'],
  },

  'major-job-change': {
    slug: 'major-job-change',
    title: 'Major Job or Income Change',
    shortTitle: 'Major Job Change',
    category: 'wealth',
    urgency: 'moderate',
    heroLine: 'A major job change — promotion, new employer, or departure — creates a cascade of financial and estate planning decisions that most people handle reactively.',
    subhead: 'Retirement account rollovers, equity compensation transitions, beneficiary updates, and insurance gaps all emerge from job changes. At the $2M–$30M level, the size of these decisions warrants deliberate planning.',
    whatChanges: [
      'Employer-provided life and disability insurance ends at termination — gap coverage must be secured immediately',
      'Unvested equity compensation may be forfeited or accelerated depending on departure terms',
      'Old 401(k) should be rolled over — leaving it with a former employer has administrative and investment risks',
      'New equity compensation (RSUs, options, ESPP) requires updated beneficiary and estate planning consideration',
      'Income change affects Social Security benefit calculations, retirement projections, and potentially estate tax threshold timing',
    ],
    actions: [
      {
        priority: 1,
        title: 'Secure individual disability and life insurance before leaving employer coverage',
        description: 'COBRA covers health insurance but not disability or life. Individual disability insurance has a 30–90 day underwriting window — start immediately.',
        linkedFeature: '/insurance',
        urgencyDays: 14,
      },
      {
        priority: 1,
        title: 'Roll over old 401(k) to an IRA or new employer plan',
        description: 'A 60-day rollover window applies for indirect rollovers. Direct rollovers have no deadline but should be completed promptly.',
        urgencyDays: 60,
        linkedFeature: '/assets',
      },
      {
        priority: 2,
        title: 'Understand unvested equity treatment under departure terms',
        description: 'Vesting acceleration, clawback provisions, and post-termination exercise windows vary by company and agreement. Know your terms.',
        professionalType: 'advisor',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Update beneficiary designations on rolled-over accounts',
        description: 'A rolled-over IRA is a new account — beneficiary designations do not transfer automatically.',
        linkedFeature: '/titling',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Update retirement projections with new income and compensation structure',
        description: 'A major income change affects your retirement timeline, Social Security benefits, and savings rate projections.',
        linkedFeature: '/projections',
      },
    ],
    assessmentQuestions: [
      {
        id: 'mj1',
        question: 'Have you secured individual disability and life insurance to replace employer coverage?',
        options: [
          { label: 'Yes — individual coverage in place', score: 3 },
          { label: 'In process of applying', score: 2 },
          { label: 'No — still on COBRA or uninsured', score: 0, hint: 'COBRA does not cover disability or life insurance' },
          { label: 'New employer coverage starts soon', score: 2 },
        ],
      },
      {
        id: 'mj2',
        question: 'Has the old employer 401(k) been rolled over?',
        options: [
          { label: 'Yes — rolled to IRA or new plan', score: 3 },
          { label: 'In process', score: 2 },
          { label: 'Still with former employer — not urgent', score: 1, hint: 'Leaving 401(k)s with former employers creates administrative risk' },
          { label: 'No 401(k) from prior employer', score: 3 },
        ],
      },
      {
        id: 'mj3',
        question: 'Do you understand the treatment of unvested equity under your departure terms?',
        options: [
          { label: 'Yes — terms reviewed with an advisor', score: 3 },
          { label: 'Generally understand my agreement', score: 2 },
          { label: 'No — haven\'t reviewed the details', score: 0, hint: 'Unvested equity can be worth significant money — or nothing' },
          { label: 'No equity compensation', score: 3 },
        ],
      },
      {
        id: 'mj4',
        question: 'Have you updated beneficiary designations on any rolled-over accounts?',
        options: [
          { label: 'Yes — new IRA has current designations', score: 3 },
          { label: 'Rollover complete but haven\'t updated designations yet', score: 1, hint: 'Beneficiary designations do not transfer in a rollover' },
          { label: 'No rollover yet', score: 2 },
          { label: 'No rollover needed', score: 3 },
        ],
      },
      {
        id: 'mj5',
        question: 'Have you updated your retirement projections for the new income and compensation structure?',
        options: [
          { label: 'Yes — projections updated', score: 3 },
          { label: 'General sense of the impact but not modeled', score: 2 },
          { label: 'No — haven\'t had time', score: 1 },
          { label: 'Income change is minimal', score: 3 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: false,
    seoTitle: 'Major Job Change: Financial and Estate Planning Checklist',
    seoDescription: 'What to do with insurance, 401(k) rollovers, equity compensation, and beneficiary designations after a major job or income change.',
    relatedSlugs: ['large-rsu-vest', 'approaching-retirement'],
  },

  'five-year-plan-review': {
    slug: 'five-year-plan-review',
    title: '5-Year Plan Review',
    shortTitle: '5-Year Review',
    category: 'retirement',
    urgency: 'moderate',
    heroLine: 'An estate plan that was right 5 years ago is probably wrong today.',
    subhead: 'Tax laws change, asset values change, family circumstances change, and relationships change. A 5-year review is the minimum cadence for a $2M–$30M household. Most people are significantly overdue.',
    whatChanges: [
      'Federal estate tax exemptions have changed — your plan may be calibrated to numbers that no longer apply',
      'Asset values have likely grown — you may be above thresholds you weren\'t near 5 years ago',
      'Beneficiary designations set years ago may no longer reflect your intentions',
      'Family circumstances — births, deaths, marriages, divorces — may require plan updates',
      'Trust structures and gifting strategies may need rebalancing given changed tax law and asset values',
    ],
    actions: [
      {
        priority: 1,
        title: 'Run an updated estate tax snapshot',
        description: 'Asset values and tax law both change. Your current estate tax exposure may be very different from what it was 5 years ago.',
        linkedFeature: '/estate-tax',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Review all beneficiary designations',
        description: 'People and priorities change. Every retirement account, life insurance policy, and financial account should be reviewed.',
        linkedFeature: '/titling',
        urgencyDays: 30,
      },
      {
        priority: 2,
        title: 'Review and update estate documents with an attorney',
        description: 'Wills, trusts, POAs, and healthcare directives should be reviewed every 3–5 years or after any major life event.',
        professionalType: 'attorney',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Review insurance coverage for adequacy',
        description: 'Life insurance face amounts, disability coverage, and umbrella limits should be revisited as assets and liabilities change.',
        linkedFeature: '/insurance',
        urgencyDays: 60,
      },
      {
        priority: 3,
        title: 'Review your retirement projections and withdrawal strategy',
        description: '5 years closer to retirement means the projections need updating. Social Security timing and withdrawal sequencing decisions may need revision.',
        linkedFeature: '/projections',
      },
    ],
    assessmentQuestions: [
      {
        id: 'fp1',
        question: 'When were your estate documents (will, trust, POA) last reviewed?',
        options: [
          { label: 'Within the last 3 years', score: 3 },
          { label: '3–5 years ago', score: 2 },
          { label: 'More than 5 years ago', score: 0, hint: 'Tax law and asset values change significantly over 5 years' },
          { label: 'Never — no estate documents', score: 0 },
        ],
      },
      {
        id: 'fp2',
        question: 'Have beneficiary designations been reviewed in the last 3 years?',
        options: [
          { label: 'Yes — reviewed and current', score: 3 },
          { label: '3–5 years ago', score: 2 },
          { label: 'More than 5 years ago', score: 0 },
          { label: 'Never reviewed', score: 0 },
        ],
      },
      {
        id: 'fp3',
        question: 'Has your estate tax exposure been modeled at your current asset level?',
        options: [
          { label: 'Yes — current snapshot in place', score: 3 },
          { label: 'Modeled years ago but not recently', score: 1, hint: 'Asset growth may have created new exposure' },
          { label: 'Never modeled', score: 0 },
          { label: 'Below all estate tax thresholds', score: 3 },
        ],
      },
      {
        id: 'fp4',
        question: 'Has your insurance coverage been reviewed for adequacy recently?',
        options: [
          { label: 'Yes — reviewed within the last 2 years', score: 3 },
          { label: '2–5 years ago', score: 2 },
          { label: 'More than 5 years ago', score: 0 },
          { label: 'No insurance to review', score: 2 },
        ],
      },
      {
        id: 'fp5',
        question: 'Have your retirement projections been updated to reflect your current situation?',
        options: [
          { label: 'Yes — updated recently with an advisor', score: 3 },
          { label: 'General sense but not formally updated', score: 2 },
          { label: 'Using projections from years ago', score: 0, hint: '5 years closer to retirement changes the math significantly' },
          { label: 'Just starting retirement planning', score: 2 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: true,
    seoTitle: '5-Year Estate Plan Review: What to Check and Update',
    seoDescription: 'Why a 5-year estate plan review matters at the $2M–$30M level. Estate tax exposure, beneficiary designations, documents, and projections.',
    relatedSlugs: ['approaching-retirement', 'estate-tax-law-change'],
  },

  'rmd-start-age': {
    slug: 'rmd-start-age',
    title: 'RMD Start Age (73)',
    shortTitle: 'RMD Start Age',
    category: 'retirement',
    urgency: 'high',
    heroLine:
      'Required Minimum Distributions begin between age 72 and 75 — and the planning decisions you make before that birthday have decade-long tax consequences.',
    subhead:
      'Your RMD start age depends on your birth year — 72, 73, or 75 under current law. For households with large tax-deferred balances, RMDs can push you into higher tax brackets, increase Medicare premiums, and create estate planning complexity. The Roth conversion window before RMDs begin is one of the highest-leverage planning opportunities available.',
    whatChanges: [
      'RMDs from traditional IRAs and 401(k)s are taxable income in the year received',
      'Large RMDs can push you into higher federal and state income tax brackets',
      'IRMAA Medicare surcharges are triggered by income thresholds — RMDs can cross those thresholds',
      'The Roth conversion window before RMDs begin (ages 72–75, depending on birth year) is often the lowest-tax period of your life',
      'First-year RMDs can be deferred to April 1 of the following year — but creates a double-RMD year',
    ],
    actions: [
      {
        priority: 1,
        title: 'Calculate your expected RMD amounts for your start age (72, 73, or 75)',
        description: 'Use the IRS Uniform Lifetime Table and your birth year to project when RMDs begin and how large they will be. For large tax-deferred balances, the amounts can be significant.',
        linkedFeature: '/rmd',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Model Roth conversion opportunities before RMDs begin',
        description: 'The gap between retirement and your RMD start age is often the lowest-tax period of your life. Converting tax-deferred assets now reduces future RMD burden.',
        linkedFeature: '/roth',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Evaluate IRMAA exposure from projected RMDs',
        description: 'Medicare Part B and D premiums increase at income thresholds. Large RMDs can trigger IRMAA surcharges of thousands per year.',
        linkedFeature: '/projections',
        urgencyDays: 90,
      },
      {
        priority: 2,
        title: 'Decide whether to defer the first RMD to April 1',
        description: 'Deferring the first RMD creates a double-RMD year. For most households, taking it in the calendar year it\'s due is simpler.',
        urgencyDays: 30,
      },
      {
        priority: 3,
        title: 'Review estate planning implications of large RMD income',
        description: 'Large taxable income from RMDs may affect your estate tax planning strategy and charitable giving opportunities.',
        professionalType: 'advisor',
      },
    ],
    assessmentQuestions: [
      {
        id: 'rs1',
        question: 'Have you calculated your expected RMD amounts for your birth-year start age (72, 73, or 75)?',
        options: [
          { label: 'Yes — projected and planning around them', score: 3 },
          { label: 'Roughly estimated', score: 2 },
          { label: 'No — haven\'t looked at this yet', score: 0, hint: 'Large RMDs can significantly affect your tax picture' },
          { label: 'Already taking RMDs', score: 3 },
        ],
      },
      {
        id: 'rs2',
        question: 'Have you evaluated Roth conversion opportunities before your RMDs begin?',
        options: [
          { label: 'Yes — conversion strategy in place', score: 3 },
          { label: 'Aware of the opportunity but haven\'t acted', score: 2 },
          { label: 'No — not familiar with the strategy', score: 0, hint: 'The pre-RMD window is often the lowest-tax period of your life' },
          { label: 'No traditional IRA or 401(k) to convert', score: 3 },
        ],
      },
      {
        id: 'rs3',
        question: 'Have you modeled IRMAA exposure from projected RMD income?',
        options: [
          { label: 'Yes — IRMAA exposure modeled and planning in place', score: 3 },
          { label: 'Aware of IRMAA but not modeled for my situation', score: 2 },
          { label: 'Not familiar with IRMAA', score: 0, hint: 'Medicare surcharges from high income can cost thousands per year' },
          { label: 'Income below IRMAA thresholds', score: 3 },
        ],
      },
      {
        id: 'rs4',
        question: 'Have you decided whether to take the first RMD in the calendar year or defer to April 1?',
        options: [
          { label: 'Yes — decision made with advisor', score: 3 },
          { label: 'Not yet — first RMD still years away', score: 2 },
          { label: 'Didn\'t know deferral was an option', score: 1 },
          { label: 'Already past first RMD year', score: 3 },
        ],
      },
      {
        id: 'rs5',
        question: 'Has your estate plan been reviewed in the context of large RMD income?',
        options: [
          { label: 'Yes — estate plan accounts for RMD income', score: 3 },
          { label: 'Estate plan exists but not reviewed for RMD impact', score: 1 },
          { label: 'No estate plan', score: 0 },
          { label: 'RMDs will be minimal', score: 3 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: false,
    seoTitle: 'RMD Start Age 73: Planning Guide for Required Minimum Distributions',
    seoDescription: 'What to do before RMDs begin at 73. Roth conversion windows, IRMAA exposure, and tax planning for required minimum distributions.',
    relatedSlugs: ['approaching-retirement', 'large-rsu-vest'],
  },

  'medicare-eligibility': {
    slug: 'medicare-eligibility',
    title: 'Medicare Eligibility (65)',
    shortTitle: 'Medicare at 65',
    category: 'retirement',
    urgency: 'high',
    heroLine: 'Missing the Medicare enrollment window at 65 causes permanent premium penalties that last for life.',
    subhead: 'The Initial Enrollment Period around your 65th birthday cannot be extended for most people. Late enrollment in Part B carries a 10% permanent penalty for each 12-month period of delay. For high-income households, IRMAA surcharges add another layer of planning complexity.',
    whatChanges: [
      'Initial Enrollment Period: 3 months before, the month of, and 3 months after your 65th birthday',
      'Part B late enrollment penalty: 10% per 12-month period of delayed enrollment — permanent',
      'Part D late enrollment penalty: 1% per month of delayed enrollment — permanent',
      'IRMAA surcharges apply to high-income beneficiaries — thresholds are based on income from 2 years prior',
      'Employer coverage rules: if still working, you may be able to delay without penalty — but the rules are specific',
    ],
    actions: [
      {
        priority: 1,
        title: 'Confirm your Initial Enrollment Period dates',
        description: 'Your window opens 3 months before your 65th birthday and closes 3 months after. Missing it has permanent consequences for most people.',
        urgencyDays: 90,
      },
      {
        priority: 1,
        title: 'Determine whether your employer coverage allows penalty-free delay',
        description: 'Only coverage from an employer where you currently work qualifies for penalty-free delay. COBRA, retiree coverage, and marketplace coverage do not.',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Model your expected IRMAA surcharges',
        description: 'IRMAA is based on income from 2 years prior. If your income was high in the look-back year, surcharges can add thousands to annual Medicare costs.',
        linkedFeature: '/projections',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Understand Medigap and Medicare Advantage enrollment rules',
        description: 'Medigap guaranteed issue rights apply only during your open enrollment window. Missing it means underwriting — and potential denial of coverage.',
        urgencyDays: 90,
      },
      {
        priority: 3,
        title: 'Coordinate Medicare with Social Security claiming strategy',
        description: 'If you delay Social Security past 65, you must enroll in Medicare separately. The coordination between these two decisions matters.',
        linkedFeature: '/social-security',
      },
    ],
    assessmentQuestions: [
      {
        id: 'me1',
        question: 'Do you know your Initial Enrollment Period dates for Medicare?',
        options: [
          { label: 'Yes — dates known and enrollment planned', score: 3 },
          { label: 'Turning 65 soon and starting to research', score: 2 },
          { label: 'No — this is the first I\'m thinking about it', score: 0, hint: 'Missing the window has permanent premium consequences' },
          { label: 'Already enrolled in Medicare', score: 3 },
        ],
      },
      {
        id: 'me2',
        question: 'If still working at 65, do you know whether your employer coverage qualifies for penalty-free delay?',
        options: [
          { label: 'Yes — confirmed with HR or benefits advisor', score: 3 },
          { label: 'Believe so but haven\'t confirmed', score: 1, hint: 'Only current employer coverage qualifies — not COBRA or retiree coverage' },
          { label: 'Retired before 65', score: 3 },
          { label: 'Not sure — need to check', score: 1 },
        ],
      },
      {
        id: 'me3',
        question: 'Have you modeled your expected IRMAA surcharges based on projected income?',
        options: [
          { label: 'Yes — IRMAA modeled and planning around it', score: 3 },
          { label: 'Aware of IRMAA but not modeled for my situation', score: 2 },
          { label: 'Not familiar with IRMAA', score: 0, hint: 'High income triggers Medicare surcharges that can cost thousands per year' },
          { label: 'Income below IRMAA thresholds', score: 3 },
        ],
      },
      {
        id: 'me4',
        question: 'Have you researched Medigap enrollment during your guaranteed issue window?',
        options: [
          { label: 'Yes — Medigap or Medicare Advantage selected', score: 3 },
          { label: 'Research in progress', score: 2 },
          { label: 'No — haven\'t started', score: 1, hint: 'Guaranteed issue rights apply only during open enrollment' },
          { label: 'Already past enrollment — coverage in place', score: 3 },
        ],
      },
      {
        id: 'me5',
        question: 'Have you coordinated Medicare enrollment with your Social Security claiming strategy?',
        options: [
          { label: 'Yes — both decisions coordinated', score: 3 },
          { label: 'Reviewed separately but not coordinated', score: 2 },
          { label: 'No — didn\'t know coordination was needed', score: 0 },
          { label: 'Already claiming Social Security', score: 3 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: false,
    seoTitle: 'Medicare Eligibility at 65: Enrollment Guide for $2M–$30M Households',
    seoDescription: 'Medicare enrollment windows, late enrollment penalties, IRMAA surcharges, and coordination with Social Security. What high-net-worth households need to know.',
    relatedSlugs: ['approaching-retirement', 'rmd-start-age'],
  },

  'social-security-timing': {
    slug: 'social-security-timing',
    title: 'Social Security Timing Decision',
    shortTitle: 'SS Timing',
    category: 'retirement',
    urgency: 'high',
    heroLine: 'The Social Security claiming decision affects lifetime income by $100K–$300K for most households — and most people make it without analysis.',
    subhead: 'Claiming at 62 vs waiting until 70 is not a simple calculation. Spousal coordination, survivor benefits, taxation of benefits, and interaction with Medicare and RMDs all affect the optimal claiming age. At the $2M–$30M level, this is a strategy decision, not a default.',
    whatChanges: [
      'Each year of delay between 62 and 70 increases your benefit by 6–8% — permanently',
      'Spousal benefits are up to 50% of the higher earner\'s benefit — claiming strategy affects both spouses',
      'Survivor benefits are based on the higher earner\'s benefit at death — delaying maximizes the survivor\'s income',
      'Social Security benefits may be taxable — up to 85% is included in income above certain thresholds',
      'Claiming before full retirement age while still working triggers earnings-based benefit reductions',
    ],
    actions: [
      {
        priority: 1,
        title: 'Model Social Security claiming scenarios for your household',
        description: 'Compare lifetime cumulative benefits across claiming ages 62–70. Include spousal coordination and survivor benefit scenarios.',
        linkedFeature: '/social-security',
        urgencyDays: 30,
      },
      {
        priority: 1,
        title: 'Coordinate claiming strategy between spouses',
        description: 'The optimal strategy for a couple is almost never for both spouses to claim at the same age. Model the combined household outcome.',
        linkedFeature: '/social-security',
        professionalType: 'advisor',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Model the interaction with RMDs and Medicare IRMAA',
        description: 'Social Security income combined with RMDs can push you above IRMAA thresholds. Model the combined income picture.',
        linkedFeature: '/projections',
        urgencyDays: 60,
      },
      {
        priority: 2,
        title: 'Understand the earnings test if claiming before full retirement age',
        description: 'If you claim before FRA and continue working, your benefit may be temporarily reduced. Understand the rules before claiming early.',
        urgencyDays: 30,
      },
      {
        priority: 3,
        title: 'Review your my.ssa.gov statement for accuracy',
        description: 'Your Social Security benefit is based on your earnings record. Errors in that record reduce your benefit. Review and dispute any inaccuracies.',
      },
    ],
    assessmentQuestions: [
      {
        id: 'ss1',
        question: 'Have you modeled Social Security claiming scenarios across different ages?',
        options: [
          { label: 'Yes — modeled with spousal coordination', score: 3 },
          { label: 'Yes — modeled for myself only', score: 2 },
          { label: 'No — plan to take it at 62 or FRA without analysis', score: 0, hint: 'The optimal age varies widely by household — analysis is essential' },
          { label: 'No — too early to think about this', score: 2 },
        ],
      },
      {
        id: 'ss2',
        question: 'If married, have you coordinated Social Security claiming strategy with your spouse?',
        options: [
          { label: 'Yes — joint strategy modeled', score: 3 },
          { label: 'Discussed generally but not formally analyzed', score: 2 },
          { label: 'No — planning to claim independently', score: 0, hint: 'Spousal coordination can add $100K+ to combined lifetime benefits' },
          { label: 'Single or widowed', score: 3 },
        ],
      },
      {
        id: 'ss3',
        question: 'Have you modeled how Social Security income interacts with RMDs and IRMAA?',
        options: [
          { label: 'Yes — combined income picture modeled', score: 3 },
          { label: 'Looked at each separately', score: 2 },
          { label: 'No — haven\'t considered the interaction', score: 0, hint: 'Combined SS and RMD income can trigger significant IRMAA surcharges' },
          { label: 'Income below relevant thresholds', score: 3 },
        ],
      },
      {
        id: 'ss4',
        question: 'Have you reviewed your my.ssa.gov earnings record for accuracy?',
        options: [
          { label: 'Yes — reviewed and confirmed accurate', score: 3 },
          { label: 'Reviewed years ago but not recently', score: 2 },
          { label: 'No — haven\'t looked at it', score: 1, hint: 'Errors in your earnings record permanently reduce your benefit' },
          { label: 'Already claiming — too late to change', score: 3 },
        ],
      },
      {
        id: 'ss5',
        question: 'Do you understand the survivor benefit implications of your claiming strategy?',
        options: [
          { label: 'Yes — survivor benefit modeled in our strategy', score: 3 },
          { label: 'Aware that it exists but not modeled', score: 2 },
          { label: 'No — hadn\'t considered survivor benefits', score: 0, hint: 'The survivor benefit can be one of the most valuable retirement assets for a couple' },
          { label: 'Single — survivor benefit not applicable', score: 3 },
        ],
      },
    ],
    advisorCTA: true,
    attorneyCTA: false,
    seoTitle: 'Social Security Timing: Claiming Strategy Guide for $2M–$30M Households',
    seoDescription: 'When to claim Social Security, spousal coordination, survivor benefits, and interaction with RMDs and Medicare. The analysis high-net-worth households need.',
    relatedSlugs: ['approaching-retirement', 'rmd-start-age', 'medicare-eligibility'],
  }
}
